// index.js
const express = require("express");
const cors = require("cors");

const app = express();
app.use(express.json());
app.use(cors());

// ✅ All Shops with 30+ products each (excluding salon and service shops)
const shops = [
  { 
    id: "1", 
    name: "Usha Store", 
    type: "shop", 
    items: [
      { id: "p1", name: "Basmati Rice 1kg", price: 90, desc: "উচ্চ মানের সুগন্ধি চাল, দৈনন্দিন রান্নার জন্য উপযুক্ত।" },
      { id: "p2", name: "Moong Dal 1kg", price: 120, desc: "প্রোটিনসমৃদ্ধ মুগ ডাল, খিচুড়ি বা তরকারির জন্য আদর্শ।" },
      { id: "p3", name: "Mustard Oil 1L", price: 150, desc: "বিশুদ্ধ সরিষার তেল, রান্না ও মালিশ দুইয়ের জন্যই ভালো।" },
      { id: "p4", name: "Wheat Flour 2kg", price: 80, desc: "তাজা গমের আটা, রুটি ও পরোটার জন্য উপযুক্ত।" },
      { id: "p5", name: "Sugar 1kg", price: 45, desc: "পরিশোধিত সাদা চিনি, চা ও মিষ্টির জন্য।" },
      { id: "p6", name: "Salt 1kg", price: 20, desc: "আয়োডিনযুক্ত লবণ, রান্নার জন্য প্রয়োজনীয়।" },
      { id: "p7", name: "Turmeric Powder 100g", price: 30, desc: "প্রাকৃতিক হলুদ গুঁড়া, রান্নায় রং ও স্বাদের জন্য।" },
      { id: "p8", name: "Red Chili Powder 100g", price: 35, desc: "তীক্ষ্ণ লাল মরিচ গুঁড়া, ঝাল স্বাদের জন্য।" },
      { id: "p9", name: "Cumin Seeds 100g", price: 25, desc: "সুগন্ধি জিরা, তরকারিতে স্বাদ বৃদ্ধির জন্য।" },
      { id: "p10", name: "Tea Leaves 250g", price: 85, desc: "উচ্চ মানের চা পাতা, সকালের সতেজতার জন্য।" },
      { id: "p11", name: "Biscuit Packet", price: 30, desc: "ক্রিম-filled বিস্কুট, স্ন্যাক্স হিসেবে উপযুক্ত।" },
      { id: "p12", name: "Soap Bar", price: 25, desc: "সুগন্ধি সাবান, ব্যক্তিগত পরিচ্ছন্নতার জন্য।" },
      { id: "p13", name: "Toor Dal 1kg", price: 110, desc: "তুর ডাল, সারা ভারতীয় রান্নার জন্য。" },
      { id: "p14", name: "Chana Dal 1kg", price: 95, desc: "ছোলার ডাল, পুষ্টিকর ও সুস্বাদু。" },
      { id: "p15", name: "Urad Dal 1kg", price: 105, desc: "উরদ ডাল, dosa ও idliএর জন্য。" },
      { id: "p16", name: "Masoor Dal 1kg", price: 85, desc: "মসুর ডাল, দ্রুত রান্না হয়。" },
      { id: "p17", name: "Cooking Oil 1L", price: 180, desc: "সূর্যমুখী তেল, রান্নার জন্য。" },
      { id: "p18", name: "Ghee 500g", price: 350, desc: "খাঁটি ঘি, বিশেষ রান্নার জন্য。" },
      { id: "p19", name: "Besan 500g", price: 60, desc: "বেসনের গুঁড়া, বিভিন্ন পদ তৈরি。" },
      { id: "p20", name: "Sooji 1kg", price: 50, desc: "সুজি, হালভা ও upmaএর জন্য。" },
      { id: "p21", name: "Poha 500g", price: 40, desc: "পোহা, সকালের নাস্তার জন্য。" },
      { id: "p22", name: "Vermicelli 500g", price: 55, desc: "সেমাই, মিষ্টি ও নোনতা উভয়ভাবেই রান্না করা যায়。" },
      { id: "p23", name: "Corn Flour 200g", price: 35, desc: "কর্ন ফ্লাওয়ার, thickening agent হিসেবে ব্যবহার。" },
      { id: "p24", name: "Baking Soda", price: 20, desc: "বেকিং সোডা, রান্না ও cleaning উভয় কাজে。" },
      { id: "p25", name: "Baking Powder", price: 25, desc: "বেকিং পাউডার, cake ও pastry তৈরিতে。" },
      { id: "p26", name: "Cocoa Powder", price: 80, desc: "কোকো পাউডার, চকলেট ফ্লেভার দেওয়ার জন্য。" },
      { id: "p27", name: "Custard Powder", price: 65, desc: "কাস্টার্ড পাউডার, মিষ্টি তৈরি করতে。" },
      { id: "p28", name: "Food Color", price: 15, desc: "খাদ্য রং, cake ও মিষ্টি রাঙানোর জন্য。" },
      { id: "p29", name: "Vinegar 500ml", price: 45, desc: "সিরকা, salad dressing ও pickle তৈরিতে。" },
      { id: "p30", name: "Soy Sauce 200ml", price: 50, desc: "সয়া সস, চাইনিজ খাবারের জন্য。" },
      { id: "p31", name: "Tomato Ketchup", price: 70, desc: "টমেটো কেচাপ, snacks এর সাথে。" },
      { id: "p32", name: "Chili Sauce", price: 55, desc: "ঝাল সস, extra spice এর জন্য。" },
      { id: "p33", name: "Mayonnaise", price: 90, desc: "মেয়োনেজ, sandwich ও salad এ。" },
      { id: "p34", name: "Pasta 500g", price: 75, desc: "পাস্তা, Italian cuisine এর জন্য。" },
      { id: "p35", name: "Noodles Pack", price: 25, desc: "ইনস্ট্যান্ট noodles, quick meal এর জন্য。" }
    ]
  },
  { 
    id: "3", 
    name: "Babuji Restaurant", 
    type: "shop", 
    items: [
      { id: "f1", name: "Chicken Biryani", price: 180, desc: "মশলাদার চিকেন বিরিয়ানি।" },
      { id: "f2", name: "Paneer Butter Masala", price: 160, desc: "নরম পনির, মাখন ও মশলার সঙ্গে রান্না।" },
      { id: "f3", name: "Veg Thali", price: 120, desc: "সম্পূর্ণ vegetarian থালি, ডাল, ভাত, সবজি, সালাদ সহ।" },
      { id: "f4", name: "Chicken Curry", price: 140, desc: "মশলাদার চিকেন কারি, ভাত বা রুটির সাথে।" },
      { id: "f5", name: "Fish Curry", price: 130, desc: "মাছের ঝোল, traditional Bengali style।" },
      { id: "f6", name: "Egg Curry", price: 70, desc: "ডিমের ঝাল ঝোল, ভাতের সাথে উপযুক্ত।" },
      { id: "f7", name: "Mixed Veg", price: 90, desc: "মিশ্র সবজির তরকারি, স্বাস্থ্যকর বিকল্প।" },
      { id: "f8", name: "Dal Fry", price: 60, desc: "সাধারণ ভাজা ডাল, ঘরোয়া স্বাদ।" },
      { id: "f9", name: "Plain Rice", price: 30, desc: "সাদা ভাত, যেকোনো তরকারির সাথে।" },
      { id: "f10", name: "Roti/Chapati", price: 10, desc: "তাজা গমের রুটি, তরকারির সাথে পরিবেশন।" },
      { id: "f11", name: "Lassi", price: 40, desc: "তাজা দইয়ের লস্সি, মিষ্টি বা নোনতা।" },
      { id: "f12", name: "Mineral Water", price: 20, desc: "বোতলজাত খাবার পানি।" },
      { id: "f13", name: "Chicken Tikka", price: 200, desc: "গ্রিল্ড চিকেন টিক্কা, spicy marinade সহ。" },
      { id: "f14", name: "Fish Fry", price: 150, desc: "ক্রিস্পি ফিশ ফ্রাই, lemon wedges সহ。" },
      { id: "f15", name: "Mutton Curry", price: 250, desc: "মাটন কারি, rich gravy সহ。" },
      { id: "f16", name: "Prawn Curry", price: 220, desc: "চিংড়ি কারি, coconut milk দিয়ে。" },
      { id: "f17", name: "Egg Biryani", price: 130, desc: "এগ বিরিয়ানি, boiled eggs সহ。" },
      { id: "f18", name: "Veg Biryani", price: 110, desc: "ভেজ বিরিয়ানি, mixed vegetables সহ。" },
      { id: "f19", name: "Chicken Korma", price: 190, desc: "চিকেন কোর্মা, mild ও creamy。" },
      { id: "f20", name: "Butter Chicken", price: 210, desc: "বাটার চিকেন, rich tomato gravy সহ。" },
      { id: "f21", name: "Tandoori Roti", price: 15, desc: "তন্দুরি রুটি, clay oven এ বেকড。" },
      { id: "f22", name: "Naan", price: 25, desc: "নান, soft ও fluffy。" },
      { id: "f23", name: "Garlic Naan", price: 35, desc: "গার্লিক নান, garlic flavor সহ。" },
      { id: "f24", name: "Butter Naan", price: 40, desc: "বাটার নান, butter brushed。" },
      { id: "f25", name: "Green Salad", price: 45, desc: "গ্রিন স্যালাড, fresh vegetables সহ。" },
      { id: "f26", name: "Raita", price: 35, desc: "রায়তা, yogurt based side dish。" },
      { id: "f27", name: "Papad", price: 10, desc: "পাপড়, crispy accompaniment。" },
      { id: "f28", name: "Pickle", price: 15, desc: "আচার, various types available。" },
      { id: "f29", name: "Chicken Soup", price: 80, desc: "চিকেন স্যুপ, hot ও comforting。" },
      { id: "f30", name: "Tomato Soup", price: 60, desc: "টমেটো স্যুপ, creamy ও delicious。" },
      { id: "f31", name: "Sweet Lassi", price: 45, desc: "সুইট লস্সি, মিষ্টি দইয়ের drink。" },
      { id: "f32", name: "Mango Lassi", price: 55, desc: "ম্যাঙ্গো লস্সি, mango pulp সহ。" },
      { id: "f33", name: "Cold Coffee", price: 65, desc: "কোল্ড কফি, ice cream সহ。" },
      { id: "f34", name: "Fresh Lime", price: 30, desc: "ফ্রেশ লাইম, refreshing drink。" },
      { id: "f35", name: "Ice Cream", price: 50, desc: "আইসক্রিম, various flavors。" }
    ]
  },
  { 
    id: "4", 
    name: "I&B Fish Center", 
    type: "shop", 
    items: [
      { id: "kf1", name: "Rohu Fish (1kg)", price: 280, desc: "তাজা নদীর রুই মাছ।" },
      { id: "kf2", name: "Katla Fish (1kg)", price: 300, desc: "বড় সাইজের কাতলা মাছ।" },
      { id: "kf3", name: "Small Prawn (500g)", price: 250, desc: "গ্রামীণ পুকুরের ছোট চিংড়ি।" },
      { id: "kf4", name: "Hilsa Fish (1kg)", price: 600, desc: "সিজনাল ইলিশ মাছ, বিশেষ স্বাদের জন্য।" },
      { id: "kf5", name: "Pabda Fish (500g)", price: 200, desc: "ছোট পাবদা মাছ, ঝোলের জন্য উপযুক্ত।" },
      { id: "kf6", name: "Tilapia Fish (1kg)", price: 180, desc: "ফার্মের তেলাপিয়া মাছ, কম কাঁটা।" },
      { id: "kf7", name: "Bhetki Fish (1kg)", price: 400, desc: "ভেটকি মাছ, ফ্রাই ও কারির জন্য।" },
      { id: "kf8", name: "Large Prawn (500g)", price: 350, desc: "বড়サイズのচিংড়ি, বিশেষ রান্নার জন্য。" },
      { id: "kf9", name: "Crab (4pcs)", price: 150, desc: "তাজা কাঁকড়া, ঝাল রান্নার জন্য。" },
      { id: "kf10", name: "Fish Cut Pieces (500g)", price: 120, desc: "মাছের কাটা টুকরো, immediate cookingএর জন্য。" },
      { id: "kf11", name: "Dry Fish (250g)", price: 80, desc: "শুঁটকি মাছ, traditional Bengali cuisineএর জন্য。" },
      { id: "kf12", name: "Fish Head (2pcs)", price: 40, desc: "মাছের মাথা, ঝোল রান্নার জন্য。" },
      { id: "kf13", name: "Pomfret Fish (1kg)", price: 450, desc: "পমফ্রেট মাছ, grilled বা fried করার জন্য。" },
      { id: "kf14", name: "Salmon Fish (1kg)", price: 800, desc: "স্যালমন মাছ, healthy omega-3 fatty acids সহ。" },
      { id: "kf15", name: "Tuna Fish (1kg)", price: 500, desc: "টুনা মাছ, protein rich。" },
      { id: "kf16", name: "Sardine Fish (1kg)", price: 220, desc: "সার্ডিন মাছ, small ও nutritious。" },
      { id: "kf17", name: "Catfish (1kg)", price: 320, desc: "ক্যাটফিশ, unique flavor সহ。" },
      { id: "kf18", name: "Anchovy (500g)", price: 180, desc: "আঙ্কোভি, small fish, frying এর জন্য。" },
      { id: "kf19", name: "Squid (500g)", price: 280, desc: "স্কুইড, seafood delicacy。" },
      { id: "kf20", name: "Octopus (500g)", price: 350, desc: "অক্টোপাস, exotic seafood。" },
      { id: "kf21", name: "Clams (1kg)", price: 200, desc: "ক্ল্যামস, shellfish variety。" },
      { id: "kf22", name: "Oysters (12pcs)", price: 400, desc: "ওয়েস্টার, premium seafood。" },
      { id: "kf23", name: "Lobster (1pc)", price: 600, desc: "লবস্টার, luxury seafood item。" },
      { id: "kf24", name: "Fish Fillet (500g)", price: 300, desc: "ফিশ ফিলেট, boneless pieces。" },
      { id: "kf25", name: "Fish Stock", price: 50, desc: "ফিশ স্টক, soup base হিসেবে。" },
      { id: "kf26", name: "Fish Marinade", price: 70, desc: "ফিশ মেরিনেড, ready-to-cook。" },
      { id: "kf27", name: "Smoked Fish", price: 380, desc: "স্মোকড ফিশ, unique flavor সহ。" },
      { id: "kf28", name: "Fish Pickle", price: 120, desc: "ফিশ পিকল, traditional accompaniment。" },
      { id: "kf29", name: "Fish Cakes (4pcs)", price: 100, desc: "ফিশ কেক, ready-to-fry。" },
      { id: "kf30", name: "Fish Balls (10pcs)", price: 80, desc: "ফিশ বল, soup বা curry এর জন্য。" },
      { id: "kf31", name: "Fish Roe (200g)", price: 150, desc: "ফিশ রো, eggs, delicacy。" },
      { id: "kf32", name: "Fish Oil Capsules", price: 200, desc: "ফিশ অয়েল ক্যাপসুল, health supplement。" },
      { id: "kf33", name: "Dried Shrimp (200g)", price: 90, desc: "শুকনো চিংড়ি, flavor enhancer。" },
      { id: "kf34", name: "Fish Sauce", price: 65, desc: "ফিশ সস, cooking ingredient。" },
      { id: "kf35", name: "Seafood Mix", price: 320, desc: "সীফুড মিক্স, variety pack。" }
    ]
  },
  { 
    id: "5", 
    name: "Susuma Tailors", 
    type: "shop", 
    items: [
      { id: "rt1", name: "Blouse Stitching", price: 200, desc: "মেয়েদের ব্লাউজ সেলাই সার্ভিস।" },
      { id: "rt2", name: "Petticoat Stitching", price: 150, desc: "কাস্টম মাপে পেটিকোট।" },
      { id: "rt3", name: "Kurta Alteration", price: 100, desc: "পুরুষদের কুর্তা কাটিং ও ঠিক করা হয়।" },
      { id: "rt4", name: "Saree Fall Stitching", price: 80, desc: "শাড়িতে ফল attach করা。" },
      { id: "rt5", name: "Shirt Stitching", price: 250, desc: "পুরুষদের ফুল শার্ট সেলাই。" },
      { id: "rt6", name: "Pant Stitching", price: 300, desc: "পুরুষদের প্যান্ট সেলাই。" },
      { id: "rt7", name: "Salwar Kameez Set", price: 500, desc: "সম্পূর্ণ সালোয়ার কামিজ সেট সেলাই。" },
      { id: "rt8", name: "Kids Dress Stitching", price: 180, desc: "বাচ্চাদের পোশাক সেলাই。" },
      { id: "rt9", name: "Zari Work Blouse", price: 400, desc: "জরির কাজ সহ ব্লাউজ সেলাই。" },
      { id: "rt10", name: "Designer Kurta", price: 350, desc: "ডিজাইনার কুর্তা সেলাই。" },
      { id: "rt11", name: "Neck Design", price: 120, desc: "ব্লাউজের নেক ডিজাইন পরিবর্তন。" },
      { id: "rt12", name: "Sleeve Alteration", price: 60, desc: "হাতা লম্বা বা ছোট করা。" },
      { id: "rt13", name: "Saree Blouse Fabric", price: 150, desc: "শাড়ি ব্লাউজের ফ্যাব্রিক, various designs。" },
      { id: "rt14", name: "Kurta Fabric", price: 200, desc: "কুর্তা ফ্যাব্রিক, cotton ও silk。" },
      { id: "rt15", name: "Shirt Fabric", price: 180, desc: "শার্ট ফ্যাব্রিক, formal ও casual。" },
      { id: "rt16", name: "Pant Fabric", price: 220, desc: "প্যান্ট ফ্যাব্রিক, different materials。" },
      { id: "rt17", name: "Salwar Fabric", price: 120, desc: "সালোয়ার ফ্যাব্রিক, comfortable materials。" },
      { id: "rt18", name: "Dupatta Fabric", price: 100, desc: "দোপাট্টা ফ্যাব্রিক, matching sets。" },
      { id: "rt19", name: "Zari Thread", price: 40, desc: "জরি থ্রেড, embroidery work এর জন্য。" },
      { id: "rt20", name: "Embroidery Thread", price: 30, desc: "এমব্রয়ডারি থ্রেড, various colors。" },
      { id: "rt21", name: "Sewing Needles", price: 15, desc: "সেলাই সুই, different sizes。" },
      { id: "rt22", name: "Tailoring Scissors", price: 80, desc: "টেইলরিং কাঁচি, professional quality。" },
      { id: "rt23", name: "Measuring Tape", price: 25, desc: "মাপার ফিতা, accurate measurements。" },
      { id: "rt24", name: "Tailoring Chalk", price: 10, desc: "টেইলরিং চক, fabric marking。" },
      { id: "rt25", name: "Pins Packet", price: 8, desc: "পিনস প্যাকেট, fabric holding。" },
      { id: "rt26", name: "Thimble", price: 12, desc: "থিম্বল, finger protection。" },
      { id: "rt27", name: "Sewing Machine Oil", price: 20, desc: "সেলাই মেশিন অয়েল, maintenance。" },
      { id: "rt28", name: "Bobbin", price: 5, desc: "ববিন, thread holder。" },
      { id: "rt29", name: "Zipper", price: 15, desc: "জিপার, different sizes ও colors。" },
      { id: "rt30", name: "Buttons Pack", price: 12, desc: "বাটন প্যাক, various designs。" },
      { id: "rt31", name: "Hook & Eye", price: 8, desc: "হুক ও আই, garment fasteners。" },
      { id: "rt32", name: "Elastic Band", price: 18, desc: "ইলাস্টিক ব্যান্ড, waistbands এর জন্য。" },
      { id: "rt33", name: "Lace Trim", price: 25, desc: "লেস ট্রিম, decorative edges。" },
      { id: "rt34", name: "Ribbon", price: 15, desc: "রিবন, various widths ও colors。" },
      { id: "rt35", name: "Fabric Glue", price: 35, desc: "ফ্যাব্রিক গ্লু, temporary fixing。" }
    ]
  },
  { 
    id: "6", 
    name: "Gopal Stationery", 
    type: "shop", 
    items: [
      { id: "gs1", name: "Notebook", price: 40, desc: "স্কুল-কলেজের জন্য ভালো মানের নোটবুক।" },
      { id: "gs2", name: "Blue Pen (Pack of 5)", price: 30, desc: "স্মুথ লিখনের পেন সেট।" },
      { id: "gs3", name: "Glue Bottle", price: 25, desc: "শিশুদের হস্তশিল্পের জন্য নিরাপদ গ্লু।" },
      { id: "gs4", name: "Pencil (Pack of 10)", price: 20, desc: "সাধারণ পেন্সিল, স্কুলের জন্য উপযুক্ত।" },
      { id: "gs5", name: "Eraser", price: 5, desc: "রাবার ইরেজার, ভুল改正ের জন্য。" },
      { id: "gs6", name: "Sharpener", price: 8, desc: "পেন্সিল শার্পনার, তীক্ষ্ণ tipএর জন্য。" },
      { id: "gs7", name: "Geometry Box", price: 80, desc: "সম্পূর্ণ জ্যামিতি বক্স, compass, protector সহ。" },
      { id: "gs8", name: "Drawing Copy", price: 35, desc: "আঁকার খাতা, শিল্পের জন্য উপযুক্ত。" },
      { id: "gs9", name: "Color Pencils (12 pcs)", price: 60, desc: "রঙিন পেন্সিল সেট, drawingএর জন্য。" },
      { id: "gs10", name: "Stapler", price: 45, desc: "ছোট স্টেপলার, কাগজ attach করার জন্য。" },
      { id: "gs11", name: "Stapler Pins", price: 10, desc: "স্টেপলার পিন, refillএর জন্য。" },
      { id: "gs12", name: "Calculator", price: 120, desc: "বেসিক ক্যালকুলেটর, গণনার জন্য。" },
      { id: "gs13", name: "Scale Set", price: 25, desc: "স্কেল সেট, different lengths。" },
      { id: "gs14", name: "Protractor", price: 15, desc: "প্রট্র্যাক্টর, angle measurement。" },
      { id: "gs15", name: "Compass", price: 20, desc: "কম্পাস, circle drawing。" },
      { id: "gs16", name: "Divider", price: 18, desc: "ডিভাইডার, measurement tool。" },
      { id: "gs17", name: "Marker Pen Set", price: 50, desc: "মার্কার পেন সেট, various colors。" },
      { id: "gs18", name: "Highlighters", price: 35, desc: "হাইলাইটার্স, text marking。" },
      { id: "gs19", name: "Sketch Pen Set", price: 45, desc: "স্কেচ পেন সেট, art work。" },
      { id: "gs20", name: "Water Colors", price: 55, desc: "ওয়াটার কালার, painting এর জন্য。" },
      { id: "gs21", name: "Poster Colors", price: 65, desc: "পোস্টার কালার, bright colors。" },
      { id: "gs22", name: "Oil Pastels", price: 70, desc: "অয়েল প্যাস্টেল, smooth coloring。" },
      { id: "gs23", name: "Crayons", price: 40, desc: "ক্রেয়নস, children's coloring。" },
      { id: "gs24", name: "Drawing Board", price: 150, desc: "ড্রইং বোর্ড, art work surface。" },
      { id: "gs25", name: "Easel", price: 300, desc: "ইজেল, canvas holding stand。" },
      { id: "gs26", name: "Canvas Sheet", price: 80, desc: "ক্যানভাস শীট, painting surface。" },
      { id: "gs27", name: "Brush Set", price: 60, desc: "ব্রাশ সেট, various sizes。" },
      { id: "gs28", name: "Palette", price: 25, desc: "প্যালেট, color mixing surface。" },
      { id: "gs29", name: "Art Paper", price: 30, desc: "আর্ট পেপার, craft work。" },
      { id: "gs30", name: "Origami Paper", price: 35, desc: "অরিগামি পেপার, paper folding art。" },
      { id: "gs31", name: "Scissors", price: 40, desc: "কাঁচি, paper cutting。" },
      { id: "gs32", name: "Paper Cutter", price: 55, desc: "পেপার কাটার, precise cutting。" },
      { id: "gs33", name: "Paper Glue", price: 20, desc: "পেপার গ্লু, craft work。" },
      { id: "gs34", name: "Sticker Sheets", price: 15, desc: "স্টিকার শীট, decorative。" },
      { id: "gs35", name: "School Bag", price: 400, desc: "স্কুল ব্যাগ, students use。" }
    ]
  },
  { 
    id: "8", 
    name: "Puja Flowers", 
    type: "shop", 
    items: [
      { id: "km1", name: "Lotus Flower", price: 20, desc: "পুজোর জন্য সতেজ পদ্মফুল।" },
      { id: "km2", name: "Garland", price: 50, desc: "তাজা ফুলের মালা।" },
      { id: "km3", name: "Incense Sticks (Packet)", price: 15, desc: "সুগন্ধি ধূপ, দৈনিক পূজার জন্য।" },
      { id: "km4", name: "Marigold Flowers", price: 25, desc: "গাঁদা ফুল, পূজা ও decorationএর জন্য。" },
      { id: "km5", name: "Rose Flowers (6pcs)", price: 30, desc: "তাজা গোলাপ ফুল, special occasionsএর জন্য。" },
      { id: "km6", name: "Jasmine Flowers", price: 35, desc: "সুগন্ধি বেলি ফুল, চুলে পরার জন্য。" },
      { id: "km7", name: "Champak Flowers", price: 28, desc: "সুগন্ধি চাঁপা ফুল, traditional পূজার জন্য。" },
      { id: "km8", name: "Tulsi Plant", price: 40, desc: "তুলসী গাছ, spiritual importance আছে。" },
      { id: "km9", name: "Camphor Tablet", price: 10, desc: "কর্পূর ট্যাবলেট, আরতি করার জন্য。" },
      { id: "km10", name: "Sacred Thread", price: 5, desc: "পবিত্র সুতা, ritualsএর জন্য。" },
      { id: "km11", name: "Puja Oil Lamp", price: 35, desc: "পূজার তেলের প্রদীপ。" },
      { id: "km12", name: "Flower Basket", price: 45, desc: "ফুলের ঝুড়ি, bulk purchaseএর জন্য。" },
      { id: "km13", name: "Lily Flowers", price: 38, desc: "লিলি ফুল, elegant decoration。" },
      { id: "km14", name: "Orchid Flowers", price: 60, desc: "অর্কিড ফুল, exotic variety。" },
      { id: "km15", name: "Sunflower", price: 32, desc: "সানফ্লাওয়ার, bright ও cheerful。" },
      { id: "km16", name: "Daisy Flowers", price: 26, desc: "ডেইজি ফুল, simple ও beautiful。" },
      { id: "km17", name: "Carnation Flowers", price: 34, desc: "কার্নেশন ফুল, long lasting。" },
      { id: "km18", name: "Hibiscus Flowers", price: 22, desc: "জবা ফুল, traditional use。" },
      { id: "km19", name: "Bouquet Small", price: 100, desc: "ছোট bouquet, gift purpose。" },
      { id: "km20", name: "Bouquet Large", price: 200, desc: "বড় bouquet, special occasions。" },
      { id: "km21", name: "Flower Vase", price: 80, desc: "ফুলদানি, flower arrangement。" },
      { id: "km22", name: "Floral Foam", price: 25, desc: "ফ্লোরাল ফোম, arrangement base。" },
      { id: "km23", name: "Ribbon Roll", price: 30, desc: "রিবন রোল, bouquet wrapping。" },
      { id: "km24", name: "Floral Tape", price: 20, desc: "ফ্লোরাল টেপ, stem binding。" },
      { id: "km25", name: "Flower Preservative", price: 15, desc: "ফুল preservative, longer life。" },
      { id: "km26", name: "Puja Bell", price: 60, desc: "পূজার ঘণ্টা, brass made。" },
      { id: "km27", name: "Brass Diya", price: 45, desc: "পিতলের দিয়া, traditional lamp。" },
      { id: "km28", name: "Clay Diya", price: 8, desc: "মাটির দিয়া, disposable。" },
      { id: "km29", name: "Wick Cotton", price: 5, desc: "সূতির বাতি, lamp lighting。" },
      { id: "km30", name: "Sandalwood Paste", price: 25, desc: "চন্দন পেস্ট, religious use。" },
      { id: "km31", name: "Kumkum", price: 12, desc: "কুমকুম, vermilion powder。" },
      { id: "km32", name: "Haldi Powder", price: 10, desc: "হলুদ গুঁড়া, turmeric。" },
      { id: "km33", name: "Chawal", price: 8, desc: "চাল, rice offerings。" },
      { id: "km34", name: "Dhoop", price: 18, desc: "ধূপ, incense cones。" },
      { id: "km35", name: "Puja Thali Set", price: 150, desc: "পূজা থালি সেট, complete setup。" }
    ]
  },
  { 
    id: "9", 
    name: "Toton Tea Stall", 
    type: "shop", 
    items: [
      { id: "rt1", name: "Milk Tea", price: 10, desc: "তাজা দুধ ও চা পাতা দিয়ে তৈরি।" },
      { id: "rt2", name: "Lemon Tea", price: 8, desc: "লেবুর হালকা চা, রিফ্রেশিং।" },
      { id: "rt3", name: "Samosa", price: 10, desc: "গরম আলুর সামোসা।" },
      { id: "rt4", name: "Biscuit (2pcs)", price: 5, desc: "সাধারণ বিস্কুট, চায়ের সাথে。" },
      { id: "rt5", name: "Toast Butter", price: 12, desc: "বাটার টোস্ট, crispy ও সুস্বাদু。" },
      { id: "rt6", name: "Egg Roll", price: 25, desc: "ডিমের রোল, তাজা vegetables সহ。" },
      { id: "rt7", name: "Chicken Roll", price: 35, desc: "চিকেন রোল, spicy filling সহ。" },
      { id: "rt8", name: "Coffee", price: 15, desc: "সাধারণ কফি, instant coffee দিয়ে তৈরি。" },
      { id: "rt9", name: "Mineral Water", price: 20, desc: "বোতলজাত পানি。" },
      { id: "rt10", name: "Cold Drink", price: 25, desc: "ঠান্ডা soft drink。" },
      { id: "rt11", name: "Pakora (4pcs)", price: 20, desc: "মিক্সড vegetable পাকোরা。" },
      { id: "rt12", name: "Special Tea", price: 15, desc: "বিশেষ মসলা চা, unique taste。" },
      { id: "rt13", name: "Masala Tea", price: 18, desc: "মসলা চা, ginger ও cardamom সহ。" },
      { id: "rt14", name: "Green Tea", price: 12, desc: "গ্রিন টি, healthy option。" },
      { id: "rt15", name: "Black Tea", price: 8, desc: "ব্ল্যাক টি, without milk。" },
      { id: "rt16", name: "Cold Tea", price: 20, desc: "কোল্ড টি, iced version。" },
      { id: "rt17", name: "Hot Coffee", price: 18, desc: "হট কফি, strong brew。" },
      { id: "rt18", name: "Cappuccino", price: 35, desc: "ক্যাপুচিনো, frothy coffee。" },
      { id: "rt19", name: "Hot Chocolate", price: 30, desc: "হট চকলেট, creamy drink。" },
      { id: "rt20", name: "Fresh Juice", price: 40, desc: "ফ্রেশ জুস, seasonal fruits。" },
      { id: "rt21", name: "Lemonade", price: 25, desc: "লেমনেড, refreshing drink。" },
      { id: "rt22", name: "Milk Shake", price: 45, desc: "মিল্ক শেক, various flavors。" },
      { id: "rt23", name: "Sandwich", price: 35, desc: "স্যান্ডউইচ, vegetable বা chicken。" },
      { id: "rt24", name: "Burger", price: 40, desc: "বার্গার, potato বা chicken patty。" },
      { id: "rt25", name: "French Fries", price: 30, desc: "ফ্রেঞ্চ ফ্রাই, crispy potatoes。" },
      { id: "rt26", name: "Onion Pakora", price: 22, desc: "পেঁয়াজ পাকোরা, onion fritters。" },
      { id: "rt27", name: "Bread Pakora", price: 18, desc: "ব্রেড পাকোরা, bread fritters。" },
      { id: "rt28", name: "Chicken Pakora", price: 28, desc: "চিকেন পাকোরা, chicken fritters。" },
      { id: "rt29", name: "Paneer Pakora", price: 25, desc: "পনির পাকোরা, cottage cheese fritters。" },
      { id: "rt30", name: "Cutlet", price: 20, desc: "কাটলেট, vegetable বা chicken。" },
      { id: "rt31", name: "Kachori", price: 15, desc: "কচুরি, stuffed pastry。" },
      { id: "rt32", name: "Mathri", price: 12, desc: "মাঠরি, savory crackers。" },
      { id: "rt33", name: "Namkeen", price: 35, desc: "নামকিন, savory snacks mix。" },
      { id: "rt34", name: "Chips Packet", price: 20, desc: "চিপস প্যাকেট, potato chips。" },
      { id: "rt35", name: "Chocolate Bar", price: 25, desc: "চকলেট বার, various brands。" }
    ]
  }
];

// ✅ API routes
app.get("/", (req, res) => res.send("✅ HaatBazar Backend is Running..."));
app.get("/shops", (req, res) => res.json(shops));
app.get("/shops/:id", (req, res) => {
  const shop = shops.find(s => s.id === req.params.id);
  if (!shop) return res.status(404).json({ message: "Shop not found" });
  res.json(shop);
});
app.post("/order", (req, res) => {
  const { items, total } = req.body;
  res.json({ message: "✅ Order received!", items, total });
});

// Run server
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running on port ${PORT}`));