// index.js
const express = require("express");
const cors = require("cors");

const app = express();
app.use(express.json());
app.use(cors());

// ✅ All Shops with 30+ products each (excluding salon and service shops)
const shops = [
  { 
    id: "1", 
    name: "Usha Store", 
    type: "shop", 
    items: [
      { id: "p1", name: "Basmati Rice 1kg", price: 90, desc: "উচ্চ মানের সুগন্ধি চাল, দৈনন্দিন রান্নার জন্য উপযুক্ত।" },
      { id: "p2", name: "Moong Dal 1kg", price: 120, desc: "প্রোটিনসমৃদ্ধ মুগ ডাল, খিচুড়ি বা তরকারির জন্য আদর্শ।" },
      { id: "p3", name: "Mustard Oil 1L", price: 150, desc: "বিশুদ্ধ সরিষার তেল, রান্না ও মালিশ দুইয়ের জন্যই ভালো।" },
      { id: "p4", name: "Wheat Flour 2kg", price: 80, desc: "তাজা গমের আটা, রুটি ও পরোটার জন্য উপযুক্ত।" },
      { id: "p5", name: "Sugar 1kg", price: 45, desc: "পরিশোধিত সাদা চিনি, চা ও মিষ্টির জন্য।" },
      { id: "p6", name: "Salt 1kg", price: 20, desc: "আয়োডিনযুক্ত লবণ, রান্নার জন্য প্রয়োজনীয়।" },
      { id: "p7", name: "Turmeric Powder 100g", price: 30, desc: "প্রাকৃতিক হলুদ গুঁড়া, রান্নায় রং ও স্বাদের জন্য।" },
      { id: "p8", name: "Red Chili Powder 100g", price: 35, desc: "তীক্ষ্ণ লাল মরিচ গুঁড়া, ঝাল স্বাদের জন্য।" },
      { id: "p9", name: "Cumin Seeds 100g", price: 25, desc: "সুগন্ধি জিরা, তরকারিতে স্বাদ বৃদ্ধির জন্য।" },
      { id: "p10", name: "Tea Leaves 250g", price: 85, desc: "উচ্চ মানের চা পাতা, সকালের সতেজতার জন্য।" },
      { id: "p11", name: "Biscuit Packet", price: 30, desc: "ক্রিম-filled বিস্কুট, স্ন্যাক্স হিসেবে উপযুক্ত।" },
      { id: "p12", name: "Soap Bar", price: 25, desc: "সুগন্ধি সাবান, ব্যক্তিগত পরিচ্ছন্নতার জন্য।" },
      { id: "p13", name: "Toor Dal 1kg", price: 110, desc: "তুর ডাল, সারা ভারতীয় রান্নার জন্য。" },
      { id: "p14", name: "Chana Dal 1kg", price: 95, desc: "ছোলার ডাল, পুষ্টিকর ও সুস্বাদু。" },
      { id: "p15", name: "Urad Dal 1kg", price: 105, desc: "উরদ ডাল, dosa ও idliএর জন্য。" },
      { id: "p16", name: "Masoor Dal 1kg", price: 85, desc: "মসুর ডাল, দ্রুত রান্না হয়。" },
      { id: "p17", name: "Cooking Oil 1L", price: 180, desc: "সূর্যমুখী তেল, রান্নার জন্য。" },
      { id: "p18", name: "Ghee 500g", price: 350, desc: "খাঁটি ঘি, বিশেষ রান্নার জন্য。" },
      { id: "p19", name: "Besan 500g", price: 60, desc: "বেসনের গুঁড়া, বিভিন্ন পদ তৈরি。" },
      { id: "p20", name: "Sooji 1kg", price: 50, desc: "সুজি, হালভা ও upmaএর জন্য。" },
      { id: "p21", name: "Poha 500g", price: 40, desc: "পোহা, সকালের নাস্তার জন্য。" },
      { id: "p22", name: "Vermicelli 500g", price: 55, desc: "সেমাই, মিষ্টি ও নোনতা উভয়ভাবেই রান্না করা যায়。" },
      { id: "p23", name: "Corn Flour 200g", price: 35, desc: "কর্ন ফ্লাওয়ার, thickening agent হিসেবে ব্যবহার。" },
      { id: "p24", name: "Baking Soda", price: 20, desc: "বেকিং সোডা, রান্না ও cleaning উভয় কাজে。" },
      { id: "p25", name: "Baking Powder", price: 25, desc: "বেকিং পাউডার, cake ও pastry তৈরিতে。" },
      { id: "p26", name: "Cocoa Powder", price: 80, desc: "কোকো পাউডার, চকলেট ফ্লেভার দেওয়ার জন্য。" },
      { id: "p27", name: "Custard Powder", price: 65, desc: "কাস্টার্ড পাউডার, মিষ্টি তৈরি করতে。" },
      { id: "p28", name: "Food Color", price: 15, desc: "খাদ্য রং, cake ও মিষ্টি রাঙানোর জন্য。" },
      { id: "p29", name: "Vinegar 500ml", price: 45, desc: "সিরকা, salad dressing ও pickle তৈরিতে。" },
      { id: "p30", name: "Soy Sauce 200ml", price: 50, desc: "সয়া সস, চাইনিজ খাবারের জন্য。" },
      { id: "p31", name: "Tomato Ketchup", price: 70, desc: "টমেটো কেচাপ, snacks এর সাথে。" },
      { id: "p32", name: "Chili Sauce", price: 55, desc: "ঝাল সস, extra spice এর জন্য。" },
      { id: "p33", name: "Mayonnaise", price: 90, desc: "মেয়োনেজ, sandwich ও salad এ。" },
      { id: "p34", name: "Pasta 500g", price: 75, desc: "পাস্তা, Italian cuisine এর জন্য。" },
      { id: "p35", name: "Noodles Pack", price: 25, desc: "ইনস্ট্যান্ট noodles, quick meal এর জন্য。" }
    ]
  },
  { 
    id: "3", 
    name: "Babuji Restaurant", 
    type: "shop", 
    items: [
      { id: "f1", name: "Chicken Biryani", price: 180, desc: "মশলাদার চিকেন বিরিয়ানি।" },
      { id: "f2", name: "Paneer Butter Masala", price: 160, desc: "নরম পনির, মাখন ও মশলার সঙ্গে রান্না।" },
      { id: "f3", name: "Veg Thali", price: 120, desc: "সম্পূর্ণ vegetarian থালি, ডাল, ভাত, সবজি, সালাদ সহ।" },
      { id: "f4", name: "Chicken Curry", price: 140, desc: "মশলাদার চিকেন কারি, ভাত বা রুটির সাথে।" },
      { id: "f5", name: "Fish Curry", price: 130, desc: "মাছের ঝোল, traditional Bengali style।" },
      { id: "f6", name: "Egg Curry", price: 70, desc: "ডিমের ঝাল ঝোল, ভাতের সাথে উপযুক্ত।" },
      { id: "f7", name: "Mixed Veg", price: 90, desc: "মিশ্র সবজির তরকারি, স্বাস্থ্যকর বিকল্প।" },
      { id: "f8", name: "Dal Fry", price: 60, desc: "সাধারণ ভাজা ডাল, ঘরোয়া স্বাদ।" },
      { id: "f9", name: "Plain Rice", price: 30, desc: "সাদা ভাত, যেকোনো তরকারির সাথে।" },
      { id: "f10", name: "Roti/Chapati", price: 10, desc: "তাজা গমের রুটি, তরকারির সাথে পরিবেশন।" },
      { id: "f11", name: "Lassi", price: 40, desc: "তাজা দইয়ের লস্সি, মিষ্টি বা নোনতা।" },
      { id: "f12", name: "Mineral Water", price: 20, desc: "বোতলজাত খাবার পানি।" },
      { id: "f13", name: "Chicken Tikka", price: 200, desc: "গ্রিল্ড চিকেন টিক্কা, spicy marinade সহ。" },
      { id: "f14", name: "Fish Fry", price: 150, desc: "ক্রিস্পি ফিশ ফ্রাই, lemon wedges সহ。" },
      { id: "f15", name: "Mutton Curry", price: 250, desc: "মাটন কারি, rich gravy সহ。" },
      { id: "f16", name: "Prawn Curry", price: 220, desc: "চিংড়ি কারি, coconut milk দিয়ে。" },
      { id: "f17", name: "Egg Biryani", price: 130, desc: "এগ বিরিয়ানি, boiled eggs সহ。" },
      { id: "f18", name: "Veg Biryani", price: 110, desc: "ভেজ বিরিয়ানি, mixed vegetables সহ。" },
      { id: "f19", name: "Chicken Korma", price: 190, desc: "চিকেন কোর্মা, mild ও creamy。" },
      { id: "f20", name: "Butter Chicken", price: 210, desc: "বাটার চিকেন, rich tomato gravy সহ。" },
      { id: "f21", name: "Tandoori Roti", price: 15, desc: "তন্দুরি রুটি, clay oven এ বেকড。" },
      { id: "f22", name: "Naan", price: 25, desc: "নান, soft ও fluffy。" },
      { id: "f23", name: "Garlic Naan", price: 35, desc: "গার্লিক নান, garlic flavor সহ。" },
      { id: "f24", name: "Butter Naan", price: 40, desc: "বাটার নান, butter brushed。" },
      { id: "f25", name: "Green Salad", price: 45, desc: "গ্রিন স্যালাড, fresh vegetables সহ。" },
      { id: "f26", name: "Raita", price: 35, desc: "রায়তা, yogurt based side dish。" },
      { id: "f27", name: "Papad", price: 10, desc: "পাপড়, crispy accompaniment。" },
      { id: "f28", name: "Pickle", price: 15, desc: "আচার, various types available。" },
      { id: "f29", name: "Chicken Soup", price: 80, desc: "চিকেন স্যুপ, hot ও comforting。" },
      { id: "f30", name: "Tomato Soup", price: 60, desc: "টমেটো স্যুপ, creamy ও delicious。" },
      { id: "f31", name: "Sweet Lassi", price: 45, desc: "সুইট লস্সি, মিষ্টি দইয়ের drink。" },
      { id: "f32", name: "Mango Lassi", price: 55, desc: "ম্যাঙ্গো লস্সি, mango pulp সহ。" },
      { id: "f33", name: "Cold Coffee", price: 65, desc: "কোল্ড কফি, ice cream সহ。" },
      { id: "f34", name: "Fresh Lime", price: 30, desc: "ফ্রেশ লাইম, refreshing drink。" },
      { id: "f35", name: "Ice Cream", price: 50, desc: "আইসক্রিম, various flavors。" }
    ]
  },
  { 
    id: "4", 
    name: "I&B Fish Center", 
    type: "shop", 
    items: [
      { id: "kf1", name: "Rohu Fish (1kg)", price: 280, desc: "তাজা নদীর রুই মাছ।" },
      { id: "kf2", name: "Katla Fish (1kg)", price: 300, desc: "বড় সাইজের কাতলা মাছ।" },
      { id: "kf3", name: "Small Prawn (500g)", price: 250, desc: "গ্রামীণ পুকুরের ছোট চিংড়ি।" },
      { id: "kf4", name: "Hilsa Fish (1kg)", price: 600, desc: "সিজনাল ইলিশ মাছ, বিশেষ স্বাদের জন্য।" },
      { id: "kf5", name: "Pabda Fish (500g)", price: 200, desc: "ছোট পাবদা মাছ, ঝোলের জন্য উপযুক্ত।" },
      { id: "kf6", name: "Tilapia Fish (1kg)", price: 180, desc: "ফার্মের তেলাপিয়া মাছ, কম কাঁটা।" },
      { id: "kf7", name: "Bhetki Fish (1kg)", price: 400, desc: "ভেটকি মাছ, ফ্রাই ও কারির জন্য।" },
      { id: "kf8", name: "Large Prawn (500g)", price: 350, desc: "বড়サイズのচিংড়ি, বিশেষ রান্নার জন্য。" },
      { id: "kf9", name: "Crab (4pcs)", price: 150, desc: "তাজা কাঁকড়া, ঝাল রান্নার জন্য。" },
      { id: "kf10", name: "Fish Cut Pieces (500g)", price: 120, desc: "মাছের কাটা টুকরো, immediate cookingএর জন্য。" },
      { id: "kf11", name: "Dry Fish (250g)", price: 80, desc: "শুঁটকি মাছ, traditional Bengali cuisineএর জন্য。" },
      { id: "kf12", name: "Fish Head (2pcs)", price: 40, desc: "মাছের মাথা, ঝোল রান্নার জন্য。" },
      { id: "kf13", name: "Pomfret Fish (1kg)", price: 450, desc: "পমফ্রেট মাছ, grilled বা fried করার জন্য。" },
      { id: "kf14", name: "Salmon Fish (1kg)", price: 800, desc: "স্যালমন মাছ, healthy omega-3 fatty acids সহ。" },
      { id: "kf15", name: "Tuna Fish (1kg)", price: 500, desc: "টুনা মাছ, protein rich。" },
      { id: "kf16", name: "Sardine Fish (1kg)", price: 220, desc: "সার্ডিন মাছ, small ও nutritious。" },
      { id: "kf17", name: "Catfish (1kg)", price: 320, desc: "ক্যাটফিশ, unique flavor সহ。" },
      { id: "kf18", name: "Anchovy (500g)", price: 180, desc: "আঙ্কোভি, small fish, frying এর জন্য。" },
      { id: "kf19", name: "Squid (500g)", price: 280, desc: "স্কুইড, seafood delicacy。" },
      { id: "kf20", name: "Octopus (500g)", price: 350, desc: "অক্টোপাস, exotic seafood。" },
      { id: "kf21", name: "Clams (1kg)", price: 200, desc: "ক্ল্যামস, shellfish variety。" },
      { id: "kf22", name: "Oysters (12pcs)", price: 400, desc: "ওয়েস্টার, premium seafood。" },
      { id: "kf23", name: "Lobster (1pc)", price: 600, desc: "লবস্টার, luxury seafood item。" },
      { id: "kf24", name: "Fish Fillet (500g)", price: 300, desc: "ফিশ ফিলেট, boneless pieces。" },
      { id: "kf25", name: "Fish Stock", price: 50, desc: "ফিশ স্টক, soup base হিসেবে。" },
      { id: "kf26", name: "Fish Marinade", price: 70, desc: "ফিশ মেরিনেড, ready-to-cook。" },
      { id: "kf27", name: "Smoked Fish", price: 380, desc: "স্মোকড ফিশ, unique flavor সহ。" },
      { id: "kf28", name: "Fish Pickle", price: 120, desc: "ফিশ পিকল, traditional accompaniment。" },
      { id: "kf29", name: "Fish Cakes (4pcs)", price: 100, desc: "ফিশ কেক, ready-to-fry。" },
      { id: "kf30", name: "Fish Balls (10pcs)", price: 80, desc: "ফিশ বল, soup বা curry এর জন্য。" },
      { id: "kf31", name: "Fish Roe (200g)", price: 150, desc: "ফিশ রো, eggs, delicacy。" },
      { id: "kf32", name: "Fish Oil Capsules", price: 200, desc: "ফিশ অয়েল ক্যাপসুল, health supplement。" },
      { id: "kf33", name: "Dried Shrimp (200g)", price: 90, desc: "শুকনো চিংড়ি, flavor enhancer。" },
      { id: "kf34", name: "Fish Sauce", price: 65, desc: "ফিশ সস, cooking ingredient。" },
      { id: "kf35", name: "Seafood Mix", price: 320, desc: "সীফুড মিক্স, variety pack。" }
    ]
  },
  { 
    id: "5", 
    name: "Susuma Tailors", 
    type: "shop", 
    items: [
      { id: "rt1", name: "Blouse Stitching", price: 200, desc: "মেয়েদের ব্লাউজ সেলাই সার্ভিস।" },
      { id: "rt2", name: "Petticoat Stitching", price: 150, desc: "কাস্টম মাপে পেটিকোট।" },
      { id: "rt3", name: "Kurta Alteration", price: 100, desc: "পুরুষদের কুর্তা কাটিং ও ঠিক করা হয়।" },
      { id: "rt4", name: "Saree Fall Stitching", price: 80, desc: "শাড়িতে ফল attach করা。" },
      { id: "rt5", name: "Shirt Stitching", price: 250, desc: "পুরুষদের ফুল শার্ট সেলাই。" },
      { id: "rt6", name: "Pant Stitching", price: 300, desc: "পুরুষদের প্যান্ট সেলাই。" },
      { id: "rt7", name: "Salwar Kameez Set", price: 500, desc: "সম্পূর্ণ সালোয়ার কামিজ সেট সেলাই。" },
      { id: "rt8", name: "Kids Dress Stitching", price: 180, desc: "বাচ্চাদের পোশাক সেলাই。" },
      { id: "rt9", name: "Zari Work Blouse", price: 400, desc: "জরির কাজ সহ ব্লাউজ সেলাই。" },
      { id: "rt10", name: "Designer Kurta", price: 350, desc: "ডিজাইনার কুর্তা সেলাই。" },
      { id: "rt11", name: "Neck Design", price: 120, desc: "ব্লাউজের নেক ডিজাইন পরিবর্তন。" },
      { id: "rt12", name: "Sleeve Alteration", price: 60, desc: "হাতা লম্বা বা ছোট করা。" },
      { id: "rt13", name: "Saree Blouse Fabric", price: 150, desc: "শাড়ি ব্লাউজের ফ্যাব্রিক, various designs。" },
      { id: "rt14", name: "Kurta Fabric", price: 200, desc: "কুর্তা ফ্যাব্রিক, cotton ও silk。" },
      { id: "rt15", name: "Shirt Fabric", price: 180, desc: "শার্ট ফ্যাব্রিক, formal ও casual。" },
      { id: "rt16", name: "Pant Fabric", price: 220, desc: "প্যান্ট ফ্যাব্রিক, different materials。" },
      { id: "rt17", name: "Salwar Fabric", price: 120, desc: "সালোয়ার ফ্যাব্রিক, comfortable materials。" },
      { id: "rt18", name: "Dupatta Fabric", price: 100, desc: "দোপাট্টা ফ্যাব্রিক, matching sets。" },
      { id: "rt19", name: "Zari Thread", price: 40, desc: "জরি থ্রেড, embroidery work এর জন্য。" },
      { id: "rt20", name: "Embroidery Thread", price: 30, desc: "এমব্রয়ডারি থ্রেড, various colors。" },
      { id: "rt21", name: "Sewing Needles", price: 15, desc: "সেলাই সুই, different sizes。" },
      { id: "rt22", name: "Tailoring Scissors", price: 80, desc: "টেইলরিং কাঁচি, professional quality。" },
      { id: "rt23", name: "Measuring Tape", price: 25, desc: "মাপার ফিতা, accurate measurements。" },
      { id: "rt24", name: "Tailoring Chalk", price: 10, desc: "টেইলরিং চক, fabric marking。" },
      { id: "rt25", name: "Pins Packet", price: 8, desc: "পিনস প্যাকেট, fabric holding。" },
      { id: "rt26", name: "Thimble", price: 12, desc: "থিম্বল, finger protection。" },
      { id: "rt27", name: "Sewing Machine Oil", price: 20, desc: "সেলাই মেশিন অয়েল, maintenance。" },
      { id: "rt28", name: "Bobbin", price: 5, desc: "ববিন, thread holder。" },
      { id: "rt29", name: "Zipper", price: 15, desc: "জিপার, different sizes ও colors。" },
      { id: "rt30", name: "Buttons Pack", price: 12, desc: "বাটন প্যাক, various designs。" },
      { id: "rt31", name: "Hook & Eye", price: 8, desc: "হুক ও আই, garment fasteners。" },
      { id: "rt32", name: "Elastic Band", price: 18, desc: "ইলাস্টিক ব্যান্ড, waistbands এর জন্য。" },
      { id: "rt33", name: "Lace Trim", price: 25, desc: "লেস ট্রিম, decorative edges。" },
      { id: "rt34", name: "Ribbon", price: 15, desc: "রিবন, various widths ও colors。" },
      { id: "rt35", name: "Fabric Glue", price: 35, desc: "ফ্যাব্রিক গ্লু, temporary fixing。" }
    ]
  },
  { 
    id: "6", 
    name: "Gopal Stationery", 
    type: "shop", 
    items: [
      { id: "gs1", name: "Notebook", price: 40, desc: "স্কুল-কলেজের জন্য ভালো মানের নোটবুক।" },
      { id: "gs2", name: "Blue Pen (Pack of 5)", price: 30, desc: "স্মুথ লিখনের পেন সেট।" },
      { id: "gs3", name: "Glue Bottle", price: 25, desc: "শিশুদের হস্তশিল্পের জন্য নিরাপদ গ্লু।" },
      { id: "gs4", name: "Pencil (Pack of 10)", price: 20, desc: "সাধারণ পেন্সিল, স্কুলের জন্য উপযুক্ত।" },
      { id: "gs5", name: "Eraser", price: 5, desc: "রাবার ইরেজার, ভুল改正ের জন্য。" },
      { id: "gs6", name: "Sharpener", price: 8, desc: "পেন্সিল শার্পনার, তীক্ষ্ণ tipএর জন্য。" },
      { id: "gs7", name: "Geometry Box", price: 80, desc: "সম্পূর্ণ জ্যামিতি বক্স, compass, protector সহ。" },
      { id: "gs8", name: "Drawing Copy", price: 35, desc: "আঁকার খাতা, শিল্পের জন্য উপযুক্ত。" },
      { id: "gs9", name: "Color Pencils (12 pcs)", price: 60, desc: "রঙিন পেন্সিল সেট, drawingএর জন্য。" },
      { id: "gs10", name: "Stapler", price: 45, desc: "ছোট স্টেপলার, কাগজ attach করার জন্য。" },
      { id: "gs11", name: "Stapler Pins", price: 10, desc: "স্টেপলার পিন, refillএর জন্য。" },
      { id: "gs12", name: "Calculator", price: 120, desc: "বেসিক ক্যালকুলেটর, গণনার জন্য。" },
      { id: "gs13", name: "Scale Set", price: 25, desc: "স্কেল সেট, different lengths。" },
      { id: "gs14", name: "Protractor", price: 15, desc: "প্রট্র্যাক্টর, angle measurement。" },
      { id: "gs15", name: "Compass", price: 20, desc: "কম্পাস, circle drawing。" },
      { id: "gs16", name: "Divider", price: 18, desc: "ডিভাইডার, measurement tool。" },
      { id: "gs17", name: "Marker Pen Set", price: 50, desc: "মার্কার পেন সেট, various colors。" },
      { id: "gs18", name: "Highlighters", price: 35, desc: "হাইলাইটার্স, text marking。" },
      { id: "gs19", name: "Sketch Pen Set", price: 45, desc: "স্কেচ পেন সেট, art work。" },
      { id: "gs20", name: "Water Colors", price: 55, desc: "ওয়াটার কালার, painting এর জন্য。" },
      { id: "gs21", name: "Poster Colors", price: 65, desc: "পোস্টার কালার, bright colors。" },
      { id: "gs22", name: "Oil Pastels", price: 70, desc: "অয়েল প্যাস্টেল, smooth coloring。" },
      { id: "gs23", name: "Crayons", price: 40, desc: "ক্রেয়নস, children's coloring。" },
      { id: "gs24", name: "Drawing Board", price: 150, desc: "ড্রইং বোর্ড, art work surface。" },
      { id: "gs25", name: "Easel", price: 300, desc: "ইজেল, canvas holding stand。" },
      { id: "gs26", name: "Canvas Sheet", price: 80, desc: "ক্যানভাস শীট, painting surface。" },
      { id: "gs27", name: "Brush Set", price: 60, desc: "ব্রাশ সেট, various sizes。" },
      { id: "gs28", name: "Palette", price: 25, desc: "প্যালেট, color mixing surface。" },
      { id: "gs29", name: "Art Paper", price: 30, desc: "আর্ট পেপার, craft work。" },
      { id: "gs30", name: "Origami Paper", price: 35, desc: "অরিগামি পেপার, paper folding art。" },
      { id: "gs31", name: "Scissors", price: 40, desc: "কাঁচি, paper cutting。" },
      { id: "gs32", name: "Paper Cutter", price: 55, desc: "পেপার কাটার, precise cutting。" },
      { id: "gs33", name: "Paper Glue", price: 20, desc: "পেপার গ্লু, craft work。" },
      { id: "gs34", name: "Sticker Sheets", price: 15, desc: "স্টিকার শীট, decorative。" },
      { id: "gs35", name: "School Bag", price: 400, desc: "স্কুল ব্যাগ, students use。" }
    ]
  },
  { 
    id: "8", 
    name: "Puja Flowers", 
    type: "shop", 
    items: [
      { id: "km1", name: "Lotus Flower", price: 20, desc: "পুজোর জন্য সতেজ পদ্মফুল।" },
      { id: "km2", name: "Garland", price: 50, desc: "তাজা ফুলের মালা।" },
      { id: "km3", name: "Incense Sticks (Packet)", price: 15, desc: "সুগন্ধি ধূপ, দৈনিক পূজার জন্য।" },
      { id: "km4", name: "Marigold Flowers", price: 25, desc: "গাঁদা ফুল, পূজা ও decorationএর জন্য。" },
      { id: "km5", name: "Rose Flowers (6pcs)", price: 30, desc: "তাজা গোলাপ ফুল, special occasionsএর জন্য。" },
      { id: "km6", name: "Jasmine Flowers", price: 35, desc: "সুগন্ধি বেলি ফুল, চুলে পরার জন্য。" },
      { id: "km7", name: "Champak Flowers", price: 28, desc: "সুগন্ধি চাঁপা ফুল, traditional পূজার জন্য。" },
      { id: "km8", name: "Tulsi Plant", price: 40, desc: "তুলসী গাছ, spiritual importance আছে。" },
      { id: "km9", name: "Camphor Tablet", price: 10, desc: "কর্পূর ট্যাবলেট, আরতি করার জন্য。" },
      { id: "km10", name: "Sacred Thread", price: 5, desc: "পবিত্র সুতা, ritualsএর জন্য。" },
      { id: "km11", name: "Puja Oil Lamp", price: 35, desc: "পূজার তেলের প্রদীপ。" },
      { id: "km12", name: "Flower Basket", price: 45, desc: "ফুলের ঝুড়ি, bulk purchaseএর জন্য。" },
      { id: "km13", name: "Lily Flowers", price: 38, desc: "লিলি ফুল, elegant decoration。" },
      { id: "km14", name: "Orchid Flowers", price: 60, desc: "অর্কিড ফুল, exotic variety。" },
      { id: "km15", name: "Sunflower", price: 32, desc: "সানফ্লাওয়ার, bright ও cheerful。" },
      { id: "km16", name: "Daisy Flowers", price: 26, desc: "ডেইজি ফুল, simple ও beautiful。" },
      { id: "km17", name: "Carnation Flowers", price: 34, desc: "কার্নেশন ফুল, long lasting。" },
      { id: "km18", name: "Hibiscus Flowers", price: 22, desc: "জবা ফুল, traditional use。" },
      { id: "km19", name: "Bouquet Small", price: 100, desc: "ছোট bouquet, gift purpose。" },
      { id: "km20", name: "Bouquet Large", price: 200, desc: "বড় bouquet, special occasions。" },
      { id: "km21", name: "Flower Vase", price: 80, desc: "ফুলদানি, flower arrangement。" },
      { id: "km22", name: "Floral Foam", price: 25, desc: "ফ্লোরাল ফোম, arrangement base。" },
      { id: "km23", name: "Ribbon Roll", price: 30, desc: "রিবন রোল, bouquet wrapping。" },
      { id: "km24", name: "Floral Tape", price: 20, desc: "ফ্লোরাল টেপ, stem binding。" },
      { id: "km25", name: "Flower Preservative", price: 15, desc: "ফুল preservative, longer life。" },
      { id: "km26", name: "Puja Bell", price: 60, desc: "পূজার ঘণ্টা, brass made。" },
      { id: "km27", name: "Brass Diya", price: 45, desc: "পিতলের দিয়া, traditional lamp。" },
      { id: "km28", name: "Clay Diya", price: 8, desc: "মাটির দিয়া, disposable。" },
      { id: "km29", name: "Wick Cotton", price: 5, desc: "সূতির বাতি, lamp lighting。" },
      { id: "km30", name: "Sandalwood Paste", price: 25, desc: "চন্দন পেস্ট, religious use。" },
      { id: "km31", name: "Kumkum", price: 12, desc: "কুমকুম, vermilion powder。" },
      { id: "km32", name: "Haldi Powder", price: 10, desc: "হলুদ গুঁড়া, turmeric。" },
      { id: "km33", name: "Chawal", price: 8, desc: "চাল, rice offerings。" },
      { id: "km34", name: "Dhoop", price: 18, desc: "ধূপ, incense cones。" },
      { id: "km35", name: "Puja Thali Set", price: 150, desc: "পূজা থালি সেট, complete setup。" }
    ]
  },
  { 
    id: "9", 
    name: "Toton Tea Stall", 
    type: "shop", 
    items: [
      { id: "rt1", name: "Milk Tea", price: 10, desc: "তাজা দুধ ও চা পাতা দিয়ে তৈরি।" },
      { id: "rt2", name: "Lemon Tea", price: 8, desc: "লেবুর হালকা চা, রিফ্রেশিং।" },
      { id: "rt3", name: "Samosa", price: 10, desc: "গরম আলুর সামোসা।" },
      { id: "rt4", name: "Biscuit (2pcs)", price: 5, desc: "সাধারণ বিস্কুট, চায়ের সাথে。" },
      { id: "rt5", name: "Toast Butter", price: 12, desc: "বাটার টোস্ট, crispy ও সুস্বাদু。" },
      { id: "rt6", name: "Egg Roll", price: 25, desc: "ডিমের রোল, তাজা vegetables সহ。" },
      { id: "rt7", name: "Chicken Roll", price: 35, desc: "চিকেন রোল, spicy filling সহ。" },
      { id: "rt8", name: "Coffee", price: 15, desc: "সাধারণ কফি, instant coffee দিয়ে তৈরি。" },
      { id: "rt9", name: "Mineral Water", price: 20, desc: "বোতলজাত পানি。" },
      { id: "rt10", name: "Cold Drink", price: 25, desc: "ঠান্ডা soft drink。" },
      { id: "rt11", name: "Pakora (4pcs)", price: 20, desc: "মিক্সড vegetable পাকোরা。" },
      { id: "rt12", name: "Special Tea", price: 15, desc: "বিশেষ মসলা চা, unique taste。" },
      { id: "rt13", name: "Masala Tea", price: 18, desc: "মসলা চা, ginger ও cardamom সহ。" },
      { id: "rt14", name: "Green Tea", price: 12, desc: "গ্রিন টি, healthy option。" },
      { id: "rt15", name: "Black Tea", price: 8, desc: "ব্ল্যাক টি, without milk。" },
      { id: "rt16", name: "Cold Tea", price: 20, desc: "কোল্ড টি, iced version。" },
      { id: "rt17", name: "Hot Coffee", price: 18, desc: "হট কফি, strong brew。" },
      { id: "rt18", name: "Cappuccino", price: 35, desc: "ক্যাপুচিনো, frothy coffee。" },
      { id: "rt19", name: "Hot Chocolate", price: 30, desc: "হট চকলেট, creamy drink。" },
      { id: "rt20", name: "Fresh Juice", price: 40, desc: "ফ্রেশ জুস, seasonal fruits。" },
      { id: "rt21", name: "Lemonade", price: 25, desc: "লেমনেড, refreshing drink。" },
      { id: "rt22", name: "Milk Shake", price: 45, desc: "মিল্ক শেক, various flavors。" },
      { id: "rt23", name: "Sandwich", price: 35, desc: "স্যান্ডউইচ, vegetable বা chicken。" },
      { id: "rt24", name: "Burger", price: 40, desc: "বার্গার, potato বা chicken patty。" },
      { id: "rt25", name: "French Fries", price: 30, desc: "ফ্রেঞ্চ ফ্রাই, crispy potatoes。" },
      { id: "rt26", name: "Onion Pakora", price: 22, desc: "পেঁয়াজ পাকোরা, onion fritters。" },
      { id: "rt27", name: "Bread Pakora", price: 18, desc: "ব্রেড পাকোরা, bread fritters。" },
      { id: "rt28", name: "Chicken Pakora", price: 28, desc: "চিকেন পাকোরা, chicken fritters。" },
      { id: "rt29", name: "Paneer Pakora", price: 25, desc: "পনির পাকোরা, cottage cheese fritters。" },
      { id: "rt30", name: "Cutlet", price: 20, desc: "কাটলেট, vegetable বা chicken。" },
      { id: "rt31", name: "Kachori", price: 15, desc: "কচুরি, stuffed pastry。" },
      { id: "rt32", name: "Mathri", price: 12, desc: "মাঠরি, savory crackers。" },
      { id: "rt33", name: "Namkeen", price: 35, desc: "নামকিন, savory snacks mix。" },
      { id: "rt34", name: "Chips Packet", price: 20, desc: "চিপস প্যাকেট, potato chips。" },
      { id: "rt35", name: "Chocolate Bar", price: 25, desc: "চকলেট বার, various brands。" }
    ]
  },
 { 
    id: "10", 
    name: "Mina Kirana Store", 
    type: "shop", 
    items: [
      { id: "mk1", name: "Toor Dal 1kg", price: 110, desc: "তুর ডাল, দক্ষিণ ভারতীয় রান্নার জন্য উপযুক্ত।" },
      { id: "mk2", name: "Chana Dal 1kg", price: 95, desc: "ছোলার ডাল, পুষ্টিকর ও সুস্বাদু।" },
      { id: "mk3", name: "Urad Dal 1kg", price: 105, desc: "উরদ ডাল, দোসা ও ইডলির জন্য।" },
      { id: "mk4", name: "Masoor Dal 1kg", price: 85, desc: "মসুর ডাল, দ্রুত রান্না হয়।" },
      { id: "mk5", name: "Cooking Oil 1L", price: 180, desc: "সূর্যমুখী তেল, রান্নার জন্য।" },
      { id: "mk6", name: "Ghee 500g", price: 350, desc: "খাঁটি ঘি, বিশেষ রান্নার জন্য।" },
      { id: "mk7", name: "Besan 500g", price: 60, desc: "বেসনের গুঁড়া, বিভিন্ন পদ তৈরি।" },
      { id: "mk8", name: "Sooji 1kg", price: 50, desc: "সুজি, হালভা ও উপমার জন্য।" },
      { id: "mk9", name: "Poha 500g", price: 40, desc: "পোহা, সকালের নাস্তার জন্য।" },
      { id: "mk10", name: "Vermicelli 500g", price: 55, desc: "সেমাই, মিষ্টি ও নোনতা উভয়ভাবেই রান্না করা যায়।" },
      { id: "mk11", name: "Corn Flour 200g", price: 35, desc: "কর্ন ফ্লাওয়ার, thickening agent হিসেবে ব্যবহার।" },
      { id: "mk12", name: "Baking Soda", price: 20, desc: "বেকিং সোডা, রান্না ও cleaning উভয় কাজে।" },
      { id: "mk13", name: "Baking Powder", price: 25, desc: "বেকিং পাউডার, cake ও pastry তৈরিতে।" },
      { id: "mk14", name: "Cocoa Powder", price: 80, desc: "কোকো পাউডার, চকলেট ফ্লেভার দেওয়ার জন্য।" },
      { id: "mk15", name: "Custard Powder", price: 65, desc: "কাস্টার্ড পাউডার, মিষ্টি তৈরি করতে।" },
      { id: "mk16", name: "Food Color", price: 15, desc: "খাদ্য রং, cake ও মিষ্টি রাঙানোর জন্য।" },
      { id: "mk17", name: "Vinegar 500ml", price: 45, desc: "সিরকা, salad dressing ও pickle তৈরিতে।" },
      { id: "mk18", name: "Soy Sauce 200ml", price: 50, desc: "সয়া সস, চাইনিজ খাবারের জন্য।" },
      { id: "mk19", name: "Tomato Ketchup", price: 70, desc: "টমেটো কেচাপ, snacks এর সাথে।" },
      { id: "mk20", name: "Chili Sauce", price: 55, desc: "ঝাল সস, extra spice এর জন্য।" },
      { id: "mk21", name: "Mayonnaise", price: 90, desc: "মেয়োনেজ, sandwich ও salad এ।" },
      { id: "mk22", name: "Pasta 500g", price: 75, desc: "পাস্তা, Italian cuisine এর জন্য।" },
      { id: "mk23", name: "Noodles Pack", price: 25, desc: "ইনস্ট্যান্ট noodles, quick meal এর জন্য।" },
      { id: "mk24", name: "Oats 500g", price: 85, desc: "ওটস, স্বাস্থ্যকর breakfast option।" },
      { id: "mk25", name: "Corn Flakes", price: 95, desc: "কর্ন ফ্লেক্স, breakfast cereal।" },
      { id: "mk26", name: "Honey 500g", price: 200, desc: "মধু, প্রাকৃতিক মিষ্টিকারক।" },
      { id: "mk27", name: "Jam Jar", price: 65, desc: "জ্যাম, bread এর সাথে।" },
      { id: "mk28", name: "Peanut Butter", price: 120, desc: "পিনাট বাটার, protein rich spread।" },
      { id: "mk29", name: "Milk Powder", price: 150, desc: "দুধ গুঁড়ো, emergency use এর জন্য।" },
      { id: "mk30", name: "Coconut Milk", price: 55, desc: "নারকেলের দুধ, curry তৈরিতে।" },
      { id: "mk31", name: "Tamarind Paste", price: 40, desc: "তেঁতুলের পেস্ট, sour flavor এর জন্য।" },
      { id: "mk32", name: "Curd Culture", price: 15, desc: "দই এর culture, homemade curd এর জন্য।" },
      { id: "mk33", name: "Papad 10pcs", price: 35, desc: "পাপড়, crispy accompaniment।" },
      { id: "mk34", name: "Fryums Packet", price: 45, desc: "ফ্রায়ামস, fried snacks।" },
      { id: "mk35", name: "Saffron Strands", price: 300, desc: "জাফরান, premium spice।" }
    ]
  },
  { 
    id: "11", 
    name: "Raju Vegetable Vendor", 
    type: "shop", 
    items: [
      { id: "rv1", name: "Potato 1kg", price: 25, desc: "তাজা আলু, সব রান্নার জন্য উপযুক্ত।" },
      { id: "rv2", name: "Onion 1kg", price: 30, desc: "পেঁয়াজ, প্রতিদিনের রান্নার জন্য।" },
      { id: "rv3", name: "Tomato 1kg", price: 40, desc: "লাল টমেটো, curry ও salad এর জন্য।" },
      { id: "rv4", name: "Cauliflower", price: 35, desc: "ফুলকপি, তরকারি ও ভাজি করার জন্য।" },
      { id: "rv5", name: "Cabbage", price: 20, desc: "বাঁধাকপি, salad ও cooked dishes এর জন্য।" },
      { id: "rv6", name: "Carrot 500g", price: 25, desc: "গাজর, salad ও cooking এর জন্য।" },
      { id: "rv7", name: "Radish 500g", price: 15, desc: "মূলা, salad ও curry এর জন্য।" },
      { id: "rv8", name: "Beetroot 500g", price: 30, desc: "বীটরুট, healthy vegetable।" },
      { id: "rv9", name: "Spinach Bunch", price: 10, desc: "পালং শাক, iron rich leafy green।" },
      { id: "rv10", name: "Coriander Bunch", price: 5, desc: "ধনিয়া পাতা, garnishing এর জন্য।" },
      { id: "rv11", name: "Mint Bunch", price: 8, desc: "পুদিনা পাতা, chutney ও drinks এর জন্য।" },
      { id: "rv12", name: "Green Chili 100g", price: 10, desc: "কাঁচা মরিচ, spicy flavor এর জন্য।" },
      { id: "rv13", name: "Lemon 4pcs", price: 12, desc: "লেবু, cooking ও drinks এর জন্য।" },
      { id: "rv14", name: "Ginger 100g", price: 20, desc: "আদা, cooking ও herbal remedies এর জন্য।" },
      { id: "rv15", name: "Garlic 100g", price: 25, desc: "রসুন, cooking এর জন্য essential।" },
      { id: "rv16", name: "Green Beans 250g", price: 18, desc: "সীমের বিচি, stir fry এর জন্য।" },
      { id: "rv17", name: "Brinjal 500g", price: 22, desc: "বেগুন, various Bengali dishes এর জন্য।" },
      { id: "rv18", name: "Pumpkin 1kg", price: 28, desc: "কুমড়া, curry ও sweet dishes এর জন্য।" },
      { id: "rv19", name: "Bitter Gourd 250g", price: 16, desc: "করলা, healthy bitter vegetable।" },
      { id: "rv20", name: "Lady Finger 250g", price: 20, desc: "ভেন্ডি, fried বা curry হিসেবে।" },
      { id: "rv21", name: "Cucumber 2pcs", price: 15, desc: "শসা, salad ও raita এর জন্য।" },
      { id: "rv22", name: "Bell Pepper 2pcs", price: 35, desc: "ক্যাপসিকাম, stir fry এর জন্য।" },
      { id: "rv23", name: "Broccoli", price: 45, desc: "ব্রোকলি, healthy green vegetable।" },
      { id: "rv24", name: "Zucchini", price: 38, desc: "জুকিনি, versatile vegetable।" },
      { id: "rv25", name: "Sweet Corn 2pcs", price: 25, desc: "মিষ্টি ভুট্টা, boiled বা grilled।" },
      { id: "rv26", name: "Spring Onion Bunch", price: 8, desc: "স্প্রিং অনিয়ন, Chinese cooking এর জন্য।" },
      { id: "rv27", name: "Celery Bunch", price: 12, desc: "সেলারি, soup ও salad এর জন্য।" },
      { id: "rv28", name: "Leek", price: 22, desc: "লিক, unique flavor vegetable।" },
      { id: "rv29", name: "Yam 500g", price: 32, desc: "যম, root vegetable।" },
      { id: "rv30", name: "Colocasia 500g", price: 28, desc: "কচু, traditional Bengali vegetable।" },
      { id: "rv31", name: "Drumsticks 4pcs", price: 18, desc: "সজনে ডাটা, curry এর জন্য।" },
      { id: "rv32", name: "Ridge Gourd", price: 14, desc: "ঝিঙে, light vegetable।" },
      { id: "rv33", name: "Snake Gourd", price: 16, desc: "চিচিঙ্গা, long gourd vegetable।" },
      { id: "rv34", name: "Ash Gourd", price: 24, desc: "চালকুমড়া, sweet dishes এর জন্য।" },
      { id: "rv35", name: "Mixed Vegetables Pack", price: 50, desc: "মিশ্র সবজি, quick cooking এর জন্য।" }
    ]
  },
  { 
    id: "12", 
    name: "Mohan Dairy", 
    type: "shop", 
    items: [
      { id: "md1", name: "Cow Milk 1L", price: 60, desc: "তাজা গরুর দুধ, প্রতিদিনের জন্য।" },
      { id: "md2", name: "Buffalo Milk 1L", price: 70, desc: "মহিষের দুধ, richer consistency।" },
      { id: "md3", name: "Curd 500g", price: 45, desc: "তাজা দই, meal accompaniment।" },
      { id: "md4", name: "Paneer 250g", price: 80, desc: "তাজা পনির, various dishes এর জন্য।" },
      { id: "md5", name: "Butter 100g", price: 50, desc: "মাখন, cooking ও spreading এর জন্য।" },
      { id: "md6", name: "Cheese Block 200g", price: 120, desc: "চিজ, sandwich ও pizza এর জন্য।" },
      { id: "md7", name: "Buttermilk 1L", price: 35, desc: "ঘোল, refreshing drink।" },
      { id: "md8", name: "Cream 200ml", price: 65, desc: "ক্রিম, dessert ও curry এর জন্য।" },
      { id: "md9", name: "Milk Powder 500g", price: 150, desc: "দুধ গুঁড়ো, emergency use এর জন্য।" },
      { id: "md10", name: "Condensed Milk", price: 85, desc: "কনডেন্সড মিল্ক, dessert তৈরিতে।" },
      { id: "md11", name: "Yogurt 500g", price: 48, desc: "দই, probiotic benefits সহ।" },
      { id: "md12", name: "Cottage Cheese", price: 75, desc: "কটেজ চিজ, healthy protein option।" },
      { id: "md13", name: "Sour Cream", price: 55, desc: "সাওয়ার ক্রিম, Mexican dishes এর জন্য।" },
      { id: "md14", name: "Whipped Cream", price: 95, desc: "হুইপড ক্রিম, dessert topping।" },
      { id: "md15", name: "Flavored Milk", price: 40, desc: "ফ্লেভার্ড মিল্ক, chocolate বা strawberry।" },
      { id: "md16", name: "Lassi 500ml", price: 45, desc: "লস্সি, sweet বা salty।" },
      { id: "md17", name: "Milkshake", price: 65, desc: "মিল্কশেক, various flavors।" },
      { id: "md18", name: "Ice Cream 500ml", price: 120, desc: "আইসক্রিম, different flavors।" },
      { id: "md19", name: "Frozen Yogurt", price: 90, desc: "ফ্রোজেন ইয়োগার্ট, healthy alternative।" },
      { id: "md20", name: "Milk Cake", price: 180, desc: "মিল্ক কেক, traditional sweet।" },
      { id: "md21", name: "Rasgulla 6pcs", price: 80, desc: "রসগোল্লা, popular Bengali sweet।" },
      { id: "md22", name: "Sandesh 8pcs", price: 75, desc: "সন্দেশ, traditional sweet।" },
      { id: "md23", name: "Rasmalai", price: 95, desc: "রসমালাই, rich milk sweet।" },
      { id: "md24", name: "Gulab Jamun 6pcs", price: 70, desc: "গুলাব জামুন, syrup soaked sweet।" },
      { id: "md25", name: "Kheer 500g", price: 60, desc: "খীর, rice pudding।" },
      { id: "md26", name: "Payasam", price: 65, desc: "পায়সাম, South Indian sweet।" },
      { id: "md27", name: "Basundi", price: 85, desc: "বসুন্দি, condensed milk sweet।" },
      { id: "md28", name: "Shrikhand", price: 75, desc: "শ্রীখণ্ড, Gujarati sweet dish।" },
      { id: "md29", name: "Milk Peda 10pcs", price: 100, desc: "মিল্ক পেডা, small sweet balls।" },
      { id: "md30", name: "Kalakand", price: 110, desc: "কালাকান্ড, milk-based sweet।" },
      { id: "md31", name: "Milk Bread", price: 40, desc: "মিল্ক ব্রেড, soft bread variety।" },
      { id: "md32", name: "Milk Biscuits", price: 30, desc: "মিল্ক বিস্কুট, tea-time snack।" },
      { id: "md33", name: "Milk Chocolate", price: 50, desc: "মিল্ক চকলেট, candy bar।" },
      { id: "md34", name: "Milk Soap", price: 35, desc: "মিল্ক সোপ, skin care soap।" },
      { id: "md35", name: "Milk Lotion", price: 85, desc: "মিল্ক লোশন, moisturizing cream।" }
    ]
  },
  { 
    id: "13", 
    name: "Bhola Fruit Center", 
    type: "shop", 
    items: [
      { id: "bf1", name: "Apple 1kg", price: 180, desc: "তাজা আপেল, স্বাস্থ্যকর ফল।" },
      { id: "bf2", name: "Banana 1dozen", price: 40, desc: "পাকা কলা, energy booster।" },
      { id: "bf3", name: "Orange 1kg", price: 120, desc: "কমলা, vitamin C rich।" },
      { id: "bf4", name: "Mango 1kg", price: 150, desc: "আম, seasonal king of fruits।" },
      { id: "bf5", name: "Pomegranate 2pcs", price: 80, desc: "আনার, antioxidant rich।" },
      { id: "bf6", name: "Grapes 500g", price: 70, desc: "আঙ্গুর, sweet ও juicy।" },
      { id: "bf7", name: "Pineapple 1pc", price: 50, desc: "আনারস, tropical fruit।" },
      { id: "bf8", name: "Watermelon 1pc", price: 60, desc: "তরমুজ, refreshing summer fruit।" },
      { id: "bf9", name: "Muskmelon 1pc", price: 45, desc: "খরবুজা, sweet melon variety।" },
      { id: "bf10", name: "Papaya 1pc", price: 35, desc: "পেঁপে, digestive benefits সহ।" },
      { id: "bf11", name: "Guava 500g", price: 30, desc: "পেয়ারা, vitamin C rich।" },
      { id: "bf12", name: "Lichi 1kg", price: 140, desc: "লিচু, seasonal summer fruit।" },
      { id: "bf13", name: "Jackfruit 1kg", price: 90, desc: "কাঁঠাল, national fruit of Bangladesh।" },
      { id: "bf14", name: "Strawberry 250g", price: 100, desc: "স্ট্রবেরি, winter season fruit।" },
      { id: "bf15", name: "Kiwi 4pcs", price: 120, desc: "কিউই, exotic fruit।" },
      { id: "bf16", name: "Dragon Fruit", price: 150, desc: "ড্রাগন ফল, unique looking fruit।" },
      { id: "bf17", name: "Avocado", price: 80, desc: "অ্যাভোকাডো, healthy fat fruit।" },
      { id: "bf18", name: "Custard Apple 500g", price: 65, desc: "শরিফা, sweet pulp fruit।" },
      { id: "bf19", name: "Sapodilla 500g", price: 55, desc: "সফেদা, brown sweet fruit।" },
      { id: "bf20", name: "Star Fruit", price: 45, desc: "কামরাঙ্গা, star-shaped fruit।" },
      { id: "bf21", name: "Pear 4pcs", price: 75, desc: "নাশপাতি, juicy fruit।" },
      { id: "bf22", name: "Plum 250g", price: 60, desc: "আলুবোখারা, small stone fruit।" },
      { id: "bf23", name: "Apricot 250g", price: 85, desc: "খুবানি, dried বা fresh।" },
      { id: "bf24", name: "Cherry 250g", price: 180, desc: "চেরি, small red fruit।" },
      { id: "bf25", name: "Blueberry 200g", price: 200, desc: "ব্লুবেরি, antioxidant rich।" },
      { id: "bf26", name: "Raspberry 200g", price: 190, desc: "রাস্পবেরি, delicate berry fruit।" },
      { id: "bf27", name: "Blackberry 200g", price: 185, desc: "ব্ল্যাকবেরি, dark berry fruit।" },
      { id: "bf28", name: "Cranberry 200g", price: 175, desc: "ক্র্যানবেরি, tart berry fruit।" },
      { id: "bf29", name: "Dates 500g", price: 220, desc: "খেজুর, natural sweetener।" },
      { id: "bf30", name: "Figs 250g", price: 160, desc: "অঞ্জির, dried fruit।" },
      { id: "bf31", name: "Raisins 250g", price: 90, desc: "কিসমিস, dried grapes।" },
      { id: "bf32", name: "Almonds 250g", price: 250, desc: "বাদাম, healthy nuts।" },
      { id: "bf33", name: "Walnuts 250g", price: 280, desc: "আখরোট, brain food nuts।" },
      { id: "bf34", name: "Cashews 250g", price: 320, desc: "কাজু বাদাম, premium nuts।" },
      { id: "bf35", name: "Pistachios 250g", price: 350, desc: "পেস্তা বাদাম, green nuts।" }
    ]
  },
  { 
    id: "14", 
    name: "Shyam Meat Shop", 
    type: "shop", 
    items: [
      { id: "sm1", name: "Chicken Whole 1kg", price: 200, desc: "সম্পূর্ণ মুরগি, তাজা ও স্বাস্থ্যকর।" },
      { id: "sm2", name: "Chicken Curry Cut 1kg", price: 220, desc: "মুরগির কাটা টুকরো, রান্নার জন্য প্রস্তুত।" },
      { id: "sm3", name: "Chicken Boneless 500g", price: 180, desc: "হাড়ছাড়া মুরগির মাংস।" },
      { id: "sm4", name: "Chicken Breast 500g", price: 200, desc: "মুরগির বুকের মাংস, lean protein।" },
      { id: "sm5", name: "Chicken Legs 500g", price: 170, desc: "মুরগির রান, juicy pieces।" },
      { id: "sm6", name: "Chicken Wings 500g", price: 160, desc: "মুরগির ডানা, fried chicken এর জন্য।" },
      { id: "sm7", name: "Chicken Liver 500g", price: 120, desc: "মুরগির কলিজা, iron rich।" },
      { id: "sm8", name: "Chicken Heart 500g", price: 110, desc: "মুরগির হৃদপিণ্ড, nutritious।" },
      { id: "sm9", name: "Mutton 1kg", price: 700, desc: "খাসির মাংস, premium quality।" },
      { id: "sm10", name: "Mutton Curry Cut 1kg", price: 720, desc: "খাসির মাংস কাটা টুকরো।" },
      { id: "sm11", name: "Mutton Boneless 500g", price: 380, desc: "হাড়ছাড়া খাসির মাংস।" },
      { id: "sm12", name: "Mutton Leg 1kg", price: 750, desc: "খাসির রান, tender meat।" },
      { id: "sm13", name: "Mutton Ribs 500g", price: 350, desc: "খাসির পাঁজর, flavorful cuts।" },
      { id: "sm14", name: "Beef 1kg", price: 500, desc: "গরুর মাংস, fresh cut।" },
      { id: "sm15", name: "Beef Curry Cut 1kg", price: 520, desc: "গরুর মাংস কাটা টুকরো।" },
      { id: "sm16", name: "Beef Boneless 500g", price: 280, desc: "হাড়ছাড়া গরুর মাংস।" },
      { id: "sm17", name: "Beef Steak 500g", price: 300, desc: "গরুর স্টেক, grilling এর জন্য।" },
      { id: "sm18", name: "Pork 1kg", price: 400, desc: "শুয়োরের মাংস, selective availability।" },
      { id: "sm19", name: "Pork Belly 500g", price: 250, desc: "শুয়োরের পেটের মাংস, bacon making।" },
      { id: "sm20", name: "Pork Chops 500g", price: 230, desc: "শুয়োরের চপস, frying এর জন্য।" },
      { id: "sm21", name: "Duck Meat 1kg", price: 450, desc: "হাঁসের মাংস, rich flavor।" },
      { id: "sm22", name: "Quail Meat 500g", price: 300, desc: "কয়েল পাখির মাংস, exotic meat।" },
      { id: "sm23", name: "Turkey Meat 1kg", price: 600, desc: "টার্কি মাংস, large bird meat।" },
      { id: "sm24", name: "Rabbit Meat 1kg", price: 550, desc: "খরগোশের মাংস, lean meat।" },
      { id: "sm25", name: "Goat Meat 1kg", price: 650, desc: "ছাগলের মাংস, common red meat।" },
      { id: "sm26", name: "Sausages 500g", price: 180, desc: "সসেজ, processed meat product।" },
      { id: "sm27", name: "Bacon 250g", price: 200, desc: "বেকন, breakfast meat।" },
      { id: "sm28", name: "Ham 250g", price: 220, desc: "হ্যাম, sliced meat।" },
      { id: "sm29", name: "Salami 250g", price: 240, desc: "সালামি, cured sausage।" },
      { id: "sm30", name: "Pepperoni 250g", price: 260, desc: "পেপারোনি, spicy sausage।" },
      { id: "sm31", name: "Meatballs 500g", price: 150, desc: "মিটবল, ready to cook।" },
      { id: "sm32", name: "Kebabs 500g", price: 170, desc: "কাবাব, minced meat preparation।" },
      { id: "sm33", name: "Minced Meat 500g", price: 160, desc: "কিমা, various dishes এর জন্য।" },
      { id: "sm34", name: "Marinated Meat 500g", price: 190, desc: "ম্যারিনেটেড মাংস, ready for cooking।" },
      { id: "sm35", name: "Frozen Meat Pack", price: 500, desc: "ফ্রোজেন মাংস প্যাক, mixed variety।" }
    ]
  },
  { 
    id: "15", 
    name: "Gouranga Sweet House", 
    type: "shop", 
    items: [
      { id: "gs1", name: "Rasgulla 6pcs", price: 80, desc: "তাজা রসগোল্লা, স্পঞ্জি ও মিষ্টি।" },
      { id: "gs2", name: "Sandesh 8pcs", price: 75, desc: "সুদেশ, দুধের মিষ্টি।" },
      { id: "gs3", name: "Rasmalai", price: 95, desc: "রসমালাই, মালাই দিয়ে তৈরি।" },
      { id: "gs4", name: "Gulab Jamun 6pcs", price: 70, desc: "গুলাব জামুন, সিরাপে ভেজানো।" },
      { id: "gs5", name: "Kalakand", price: 110, desc: "কালাকান্ড, দুধের কাটা মিষ্টি।" },
      { id: "gs6", name: "Milk Cake", price: 180, desc: "মিল্ক কেক, নরম ও মিষ্টি।" },
      { id: "gs7", name: "Cham Cham 6pcs", price: 85, desc: "চমচম, লম্বা মিষ্টি।" },
      { id: "gs8", name: "Pantua 6pcs", price: 75, desc: "পান্তুয়া, বাঙালি মিষ্টি।" },
      { id: "gs9", name: "Ledikeni", price: 90, desc: "লেডিকেনি, ঐতিহ্যবাহী মিষ্টি।" },
      { id: "gs10", name: "Mihidana", price: 65, desc: "মিহিদানা, ছোট মিষ্টি দানা।" },
      { id: "gs11", name: "Sitabhog", price: 70, desc: "সীতাভোগ, চালের গুঁড়ার মিষ্টি।" },
      { id: "gs12", name: "Malpua 4pcs", price: 60, desc: "মালপুয়া, fried sweet pancake।" },
      { id: "gs13", name: "Kheer 500g", price: 60, desc: "খীর, rice pudding।" },
      { id: "gs14", name: "Payesh", price: 65, desc: "পায়েশ, বাঙালি rice pudding।" },
      { id: "gs15", name: "Basundi", price: 85, desc: "বসুন্দি, condensed milk sweet।" },
      { id: "gs16", name: "Shrikhand", price: 75, desc: "শ্রীখণ্ড, Gujarati sweet dish।" },
      { id: "gs17", name: "Halwa 500g", price: 55, desc: "হালভা, semolina sweet।" },
      { id: "gs18", name: "Gajar Halwa", price: 95, desc: "গাজর হালভা, winter special।" },
      { id: "gs19", name: "Moong Dal Halwa", price: 85, desc: "মুগ ডাল হালভা, rich sweet।" },
      { id: "gs20", name: "Badam Halwa", price: 120, desc: "বাদাম হালভা, almond sweet।" },
      { id: "gs21", name: "Laddu 6pcs", price: 50, desc: "লাড্ডু, round sweet balls।" },
      { id: "gs22", name: "Moti Chur Laddu", price: 65, desc: "মোতি চুর লাড্ডু, pearl-like sweet।" },
      { id: "gs23", name: "Besan Laddu", price: 60, desc: "বেসন লাড্ডু, gram flour sweet।" },
      { id: "gs24", name: "Coconut Laddu", price: 55, desc: "নারকেল লাড্ডু, coconut sweet।" },
      { id: "gs25", name: "Jalebi 250g", price: 45, desc: "জিলাপি, crispy spiral sweet।" },
      { id: "gs26", name: "Imarti", price: 48, desc: "ইমারতি, flower-shaped sweet।" },
      { id: "gs27", name: "Barfi 500g", price: 70, desc: "বারফি, milk solid sweet।" },
      { id: "gs28", name: "Kaju Barfi", price: 130, desc: "কাজু বারফি, cashew sweet।" },
      { id: "gs29", name: "Pista Barfi", price: 140, desc: "পিস্তা বারফি, pistachio sweet।" },
      { id: "gs30", name: "Chocolate Barfi", price: 90, desc: "চকলেট বারফি, chocolate flavor।" },
      { id: "gs31", name: "Soan Papdi", price: 40, desc: "সোয়ান পাপড়ি, flaky sweet।" },
      { id: "gs32", name: "Peda 10pcs", price: 100, desc: "পেডা, small sweet discs।" },
      { id: "gs33", name: "Mathri", price: 35, desc: "মাঠরি, savory sweet mix।" },
      { id: "gs34", name: "Nankhatai", price: 45, desc: "নানখাটাই, Indian cookies।" },
      { id: "gs35", name: "Sweet Box", price: 250, desc: "মিষ্টির বক্স, assorted sweets।" }
    ]
  },
  { 
    id: "16", 
    name: "Bharat Hardware", 
    type: "shop", 
    items: [
      { id: "bh1", name: "Hammer", price: 150, desc: "হাতুড়ি, সাধারণ কাজের জন্য।" },
      { id: "bh2", name: "Screwdriver Set", price: 120, desc: "স্ক্রুড্রাইভার সেট, বিভিন্ন size এর।" },
      { id: "bh3", name: "Pliers", price: 100, desc: "প্লাইয়ার, wire cutting এর জন্য।" },
      { id: "bh4", name: "Wrench Set", price: 180, desc: "রেঞ্চ সেট, nuts ও bolts এর জন্য।" },
      { id: "bh5", name: "Measuring Tape", price: 80, desc: "মাপার ফিতা, accurate measurement।" },
      { id: "bh6", name: "Spanner Set", price: 220, desc: "স্প্যানার সেট, different sizes।" },
      { id: "bh7", name: "Nails 1kg", price: 60, desc: "পেরেক, বিভিন্ন size এর।" },
      { id: "bh8", name: "Screws Pack", price: 45, desc: "স্ক্রু প্যাক, বিভিন্ন ধরনের।" },
      { id: "bh9", name: "Nuts & Bolts Set", price: 75, desc: "নাট ও বোল্ট সেট, fixing এর জন্য।" },
      { id: "bh10", name: "Drill Machine", price: 1200, desc: "ড্রিল মেশিন, hole making।" },
      { id: "bh11", name: "Drill Bits Set", price: 150, desc: "ড্রিল বিট সেট, different sizes।" },
      { id: "bh12", name: "Saw", price: 200, desc: "করাত, wood cutting।" },
      { id: "bh13", name: "Chisel Set", price: 130, desc: "ছেনি সেট, wood carving।" },
      { id: "bh14", name: "File Set", price: 90, desc: "ফাইল সেট, metal smoothing।" },
      { id: "bh15", name: "Vice", price: 350, desc: "বিশ, holding workpiece।" },
      { id: "bh16", name: "Ladder 6ft", price: 800, desc: "সিঁড়ি, reaching height।" },
      { id: "bh17", name: "Tool Box", price: 250, desc: "টুল বক্স, tools storage।" },
      { id: "bh18", name: "Safety Gloves", price: 40, desc: "সেফটি গ্লাভস, hand protection।" },
      { id: "bh19", name: "Safety Goggles", price: 60, desc: "সেফটি গগলস, eye protection।" },
      { id: "bh20", name: "Work Apron", price: 120, desc: "ওয়ার্ক এপ্রন, clothing protection।" },
      { id: "bh21", name: "Electric Wire Roll", price: 180, desc: "ইলেকট্রিক তার, electrical work।" },
      { id: "bh22", name: "Switch Socket", price: 35, desc: "সুইচ সকেট, electrical fitting।" },
      { id: "bh23", name: "Bulb 40W", price: 25, desc: "বাল্ব, lighting purpose।" },
      { id: "bh24", name: "Tube Light", price: 85, desc: "টিউব লাইট, bright lighting।" },
      { id: "bh25", name: "Fuse Wire", price: 15, desc: "ফিউজ তার, electrical safety।" },
      { id: "bh26", name: "Multimeter", price: 300, desc: "মাল্টিমিটার, electrical testing।" },
      { id: "bh27", name: "Test Pen", price: 20, desc: "টেস্ট পেন, voltage testing।" },
      { id: "bh28", name: "Pipe Cutter", price: 110, desc: "পাইপ কাটার, pipe cutting tool।" },
      { id: "bh29", name: "Pipe Wrench", price: 140, desc: "পাইপ রেঞ্চ, plumbing work।" },
      { id: "bh30", name: "Teflon Tape", price: 12, desc: "টেফলন টেপ, pipe sealing।" },
      { id: "bh31", name: "PVC Pipe 6ft", price: 65, desc: "PVC পাইপ, plumbing use।" },
      { id: "bh32", name: "Pipe Fittings", price: 30, desc: "পাইপ ফিটিংস, connection pieces।" },
      { id: "bh33", name: "Water Tap", price: 95, desc: "জলের নল, water supply।" },
      { id: "bh34", name: "Shower Head", price: 120, desc: "শাওয়ার হেড, bathroom fitting।" },
      { id: "bh35", name: "Tool Kit Set", price: 500, desc: "টুল কিট সেট, complete hardware kit।" }
    ]
  },
  { 
    id: "17", 
    name: "Sita Beauty Parlor", 
    type: "shop", 
    items: [
      { id: "sb1", name: "Shampoo 100ml", price: 45, desc: "শ্যাম্পু, চুল পরিষ্কারের জন্য।" },
      { id: "sb2", name: "Conditioner 100ml", price: 50, desc: "কন্ডিশনার, চুল নরম করার জন্য।" },
      { id: "sb3", name: "Hair Oil 200ml", price: 65, desc: "চুলের তেল, nourishment এর জন্য।" },
      { id: "sb4", name: "Hair Serum", price: 85, desc: "হেয়ার সিরাম, frizz control।" },
      { id: "sb5", name: "Hair Mask", price: 120, desc: "হেয়ার মাস্ক, deep conditioning।" },
      { id: "sb6", name: "Hair Color Pack", price: 150, desc: "হেয়ার কালার, different shades।" },
      { id: "sb7", name: "Hair Spray", price: 95, desc: "হেয়ার স্প্রে, styling hold।" },
      { id: "sb8", name: "Hair Gel", price: 70, desc: "হেয়ার জেল, styling product।" },
      { id: "sb9", name: "Hair Mousse", price: 110, desc: "হেয়ার মাউস, volume creating।" },
      { id: "sb10", name: "Hair Wax", price: 90, desc: "হেয়ার ওয়াক্স, texturizing product।" },
      { id: "sb11", name: "Face Wash", price: 55, desc: "ফেস ওয়াশ, face cleansing।" },
      { id: "sb12", name: "Face Cream", price: 75, desc: "ফেস ক্রিম, moisturizing।" },
      { id: "sb13", name: "Sunscreen Lotion", price: 95, desc: "সানস্ক্রিন, UV protection।" },
      { id: "sb14", name: "Face Pack", price: 65, desc: "ফেস প্যাক, skin treatment।" },
      { id: "sb15", name: "Face Scrub", price: 60, desc: "ফেস স্ক্রাব, exfoliation।" },
      { id: "sb16", name: "Toner", price: 70, desc: "টোনার, skin balancing।" },
      { id: "sb17", name: "Makeup Remover", price: 55, desc: "মেকআপ রিমুভার, cleansing oil।" },
      { id: "sb18", name: "Foundation", price: 130, desc: "ফাউন্ডেশন, base makeup।" },
      { id: "sb19", name: "Compact Powder", price: 85, desc: "কম্প্যাক্ট পাউডার, setting makeup।" },
      { id: "sb20", name: "Lipstick", price: 65, desc: "লিপস্টিক, color variety।" },
      { id: "sb21", name: "Lip Gloss", price: 55, desc: "লিপ গ্লস, shiny finish।" },
      { id: "sb22", name: "Kajal", price: 35, desc: "কাজল, eye lining।" },
      { id: "sb23", name: "Eyeliner", price: 45, desc: "আইলাইনার, eye definition।" },
      { id: "sb24", name: "Mascara", price: 95, desc: "মাস্কারা, eyelash enhancing।" },
      { id: "sb25", name: "Eyeshadow Palette", price: 180, desc: "আইশ্যাডো প্যালেট, color options।" },
      { id: "sb26", name: "Blush", price: 75, desc: "ব্লাশ, cheek color।" },
      { id: "sb27", name: "Nail Polish", price: 40, desc: "নেইল পলিশ, nail color।" },
      { id: "sb28", name: "Nail Polish Remover", price: 30, desc: "নেইল পলিশ রিমুভার, cleansing।" },
      { id: "sb29", name: "Perfume 50ml", price: 200, desc: "পারফিউম, fragrance spray।" },
      { id: "sb30", name: "Deodorant", price: 65, desc: "ডিওডোরেন্ট, body odor protection।" },
      { id: "sb31", name: "Body Lotion", price: 85, desc: "বডি লোশন, skin moisturizing।" },
      { id: "sb32", name: "Body Wash", price: 70, desc: "বডি ওয়াশ, shower gel।" },
      { id: "sb33", name: "Body Scrub", price: 95, desc: "বডি স্ক্রাব, exfoliation।" },
      { id: "sb34", name: "Bath Salt", price: 55, desc: "বাথ সল্ট, relaxing bath।" },
      { id: "sb35", name: "Beauty Kit", price: 350, desc: "বিউটি কিট, complete set।" }
    ]
  },
  { 
    id: "18", 
    name: "Rahim Electricals", 
    type: "shop", 
    items: [
      { id: "re1", name: "Ceiling Fan", price: 1200, desc: "সিলিং ফ্যান, room cooling।" },
      { id: "re2", name: "Table Fan", price: 650, desc: "টেবিল ফ্যান, personal use।" },
      { id: "re3", name: "Exhaust Fan", price: 450, desc: "এক্সহস্ট ফ্যান, ventilation।" },
      { id: "re4", name: "LED Bulb 9W", price: 85, desc: "LED বাল্ব, energy saving।" },
      { id: "re5", name: "Tube Light 20W", price: 120, desc: "টিউব লাইট, bright lighting।" },
      { id: "re6", name: "LED Panel Light", price: 180, desc: "LED প্যানেল লাইট, modern lighting।" },
      { id: "re7", name: "Switch Socket", price: 35, desc: "সুইচ সকেট, electrical fitting।" },
      { id: "re8", name: "Extension Board", price: 150, desc: "এক্সটেনশন বোর্ড, multiple plug points।" },
      { id: "re9", name: "Electric Wire Roll", price: 180, desc: "ইলেকট্রিক তার, wiring work।" },
      { id: "re10", name: "MCB 16A", price: 95, desc: "MCB, electrical safety device।" },
      { id: "re11", name: "Electric Iron", price: 350, desc: "ইলেকট্রিক ইস্ত্রি, clothes ironing।" },
      { id: "re12", name: "Water Heater", price: 1200, desc: "ওয়াটার হিটার, hot water geyser।" },
      { id: "re13", name: "Immersion Rod", price: 250, desc: "ইমারশন রড, water heating।" },
      { id: "re14", name: "Electric Kettle", price: 450, desc: "ইলেকট্রিক কেটলি, water boiling।" },
      { id: "re15", name: "Toaster", price: 550, desc: "টোস্টার, bread toasting।" },
      { id: "re16", name: "Mixer Grinder", price: 1200, desc: "মিক্সার গ্রাইন্ডার, kitchen appliance।" },
      { id: "re17", name: "Blender", price: 850, desc: "ব্লেন্ডার, juice making।" },
      { id: "re18", name: "Rice Cooker", price: 950, desc: "রাইস কুকার, automatic rice cooking।" },
      { id: "re19", name: "Induction Cooktop", price: 1300, desc: "ইন্ডাকশন কুকটপ, modern cooking।" },
      { id: "re20", name: "Microwave Oven", price: 2500, desc: "মাইক্রোওয়েভ ওভেন, quick heating।" },
      { id: "re21", name: "Refrigerator", price: 8500, desc: "রেফ্রিজারেটর, food preservation।" },
      { id: "re22", name: "Washing Machine", price: 6500, desc: "ওয়াশিং মেশিন, clothes washing।" },
      { id: "re23", name: "Air Cooler", price: 2800, desc: "এয়ার কুলার, room cooling।" },
      { id: "re24", name: "AC 1 Ton", price: 12000, desc: "এয়ার কন্ডিশনার, room cooling।" },
      { id: "re25", name: "Stabilizer", price: 650, desc: "স্টেবিলাইজার, voltage regulation।" },
      { id: "re26", name: "Inverter", price: 4500, desc: "ইনভার্টার, power backup।" },
      { id: "re27", name: "Battery", price: 3200, desc: "ব্যাটারি, power storage।" },
      { id: "re28", name: "Solar Panel", price: 2800, desc: "সোলার প্যানেল, solar energy।" },
      { id: "re29", name: "LED TV 32inch", price: 8500, desc: "LED TV, entertainment।" },
      { id: "re30", name: "Set Top Box", price: 650, desc: "সেট টপ বক্স, TV connection।" },
      { id: "re31", name: "Router", price: 950, desc: "রাউটার, internet connection।" },
      { id: "re32", name: "Mobile Charger", price: 120, desc: "মোবাইল চার্জার, phone charging।" },
      { id: "re33", name: "Power Bank", price: 650, desc: "পাওয়ার ব্যাংক, portable charging।" },
      { id: "re34", name: "Headphones", price: 350, desc: "হেডফোনস, audio listening।" },
      { id: "re35", name: "Electrical Tool Kit", price: 850, desc: "ইলেকট্রিক্যাল টুল কিট, repair work।" }
    ]
  },
  { 
    id: "19", 
    name: "Kamal Pharmacy", 
    type: "shop", 
    items: [
      { id: "kp1", name: "Paracetamol 10pcs", price: 15, desc: "প্যারাসিটামল, জ্বর ও ব্যথার জন্য।" },
      { id: "kp2", name: "Aspirin 10pcs", price: 20, desc: "অ্যাসপিরিন, ব্যথানাশক।" },
      { id: "kp3", name: "Antacid Tablets", price: 25, desc: "অ্যান্টাসিড, অম্লনাশক।" },
      { id: "kp4", name: "Digene 10pcs", price: 30, desc: "ডাইজিন, acidity relief।" },
      { id: "kp5", name: "Crocin 10pcs", price: 18, desc: "ক্রোসিন, fever medicine।" },
      { id: "kp6", name: "Combiflam 10pcs", price: 35, desc: "কম্বিফ্লাম, pain relief।" },
      { id: "kp7", name: "Dettol 100ml", price: 45, desc: "ডেটল, antiseptic liquid।" },
      { id: "kp8", name: "Bandage Roll", price: 25, desc: "ব্যান্ডেজ, wound dressing।" },
      { id: "kp9", name: "Cotton Wool 100g", price: 30, desc: "কটন উল, medical use।" },
      { id: "kp10", name: "Gauze Piece", price: 20, desc: "গজ, wound care।" },
      { id: "kp11", name: "Betadine Ointment", price: 55, desc: "বিটাডিন অইন্টমেন্ট, antiseptic cream।" },
      { id: "kp12", name: "Moov Spray", price: 120, desc: "মুভ স্প্রে, pain relief spray।" },
      { id: "kp13", name: "Volini Gel", price: 95, desc: "ভোলিনি জেল, muscle pain relief।" },
      { id: "kp14", name: "Iodex 50g", price: 45, desc: "আইওডেক্স, pain relief ointment।" },
      { id: "kp15", name: "Burnol Cream", price: 35, desc: "বার্নল ক্রিম, burn treatment।" },
      { id: "kp16", name: "ORS Packet", price: 15, desc: "ORS, dehydration treatment।" },
      { id: "kp17", name: "Electral Powder", price: 20, desc: "ইলেক্ট্রাল পাউডার, electrolyte balance।" },
      { id: "kp18", name: "Vitamin C Tablets", price: 40, desc: "ভিটামিন সি ট্যাবলেট, immunity booster।" },
      { id: "kp19", name: "Multivitamin Capsules", price: 65, desc: "মাল্টিভিটামিন ক্যাপসুল, overall health।" },
      { id: "kp20", name: "Calcium Tablets", price: 55, desc: "ক্যালসিয়াম ট্যাবলেট, bone health।" },
      { id: "kp21", name: "Iron Supplements", price: 50, desc: "আয়রন সাপ্লিমেন্ট, blood health।" },
      { id: "kp22", name: "Protein Powder", price: 350, desc: "প্রোটিন পাউডার, muscle building।" },
      { id: "kp23", name: "Cough Syrup", price: 75, desc: "কফ সিরাপ, cough relief।" },
      { id: "kp24", name: "Cold Capsules", price: 30, desc: "কোল্ড ক্যাপসুল, cold treatment।" },
      { id: "kp25", name: "Allergy Tablets", price: 40, desc: "অ্যালার্জি ট্যাবলেট, allergy relief।" },
      { id: "kp26", name: "Asthma Inhaler", price: 180, desc: "অ্যাস্থমা ইনহেলার, breathing aid।" },
      { id: "kp27", name: "Diabetes Strips", price: 250, desc: "ডায়াবেটিস স্ট্রিপস, sugar testing।" },
      { id: "kp28", name: "BP Monitor", price: 850, desc: "BP মনিটর, blood pressure check।" },
      { id: "kp29", name: "Thermometer", price: 65, desc: "থার্মোমিটার, body temperature।" },
      { id: "kp30", name: "First Aid Kit", price: 200, desc: "ফার্স্ট এইড কিট, emergency medical kit।" },
      { id: "kp31", name: "Baby Powder", price: 45, desc: "বেবি পাউডার, baby care।" },
      { id: "kp32", name: "Diapers Pack", price: 180, desc: "ডায়াপার্স প্যাক, baby use।" },
      { id: "kp33", name: "Baby Oil", price: 65, desc: "বেবি অয়েল, skin care।" },
      { id: "kp34", name: "Baby Lotion", price: 75, desc: "বেবি লোশন, moisturizing।" },
      { id: "kp35", name: "Baby Shampoo", price: 55, desc: "বেবি শ্যাম্পু, gentle cleansing।" }
    ]
  },
  { 
    id: "20", 
    name: "Nutan Bakery", 
    type: "shop", 
    items: [
      { id: "nb1", name: "White Bread", price: 35, desc: "সাদা পাউরুটি, তাজা বেকড।" },
      { id: "nb2", name: "Brown Bread", price: 40, desc: "বাদামি পাউরুটি, স্বাস্থ্যকর option।" },
      { id: "nb3", name: "Bun 6pcs", price: 25, desc: "বান, burger বা sandwich এর জন্য।" },
      { id: "nb4", name: "Pav 8pcs", price: 20, desc: "পাঁউ, pav bhaji এর জন্য।" },
      { id: "nb5", name: "Cake Slice", price: 30, desc: "কেক স্লাইস, different flavors।" },
      { id: "nb6", name: "Whole Cake 500g", price: 250, desc: "সম্পূর্ণ কেক, special occasions।" },
      { id: "nb7", name: "Cupcakes 4pcs", price: 60, desc: "কাপকেকস, small individual cakes।" },
      { id: "nb8", name: "Cookies 250g", price: 45, desc: "কুকিজ, tea-time snack।" },
      { id: "nb9", name: "Biscuits Pack", price: 30, desc: "বিস্কুট প্যাক, various types।" },
      { id: "nb10", name: "Rusk 250g", price: 35, desc: "রাস্ক, crispy baked bread।" },
      { id: "nb11", name: "Toast Bread", price: 38, desc: "টোস্ট ব্রেড, toasting এর জন্য।" },
      { id: "nb12", name: "Garlic Bread", price: 55, desc: "গার্লিক ব্রেড, Italian style।" },
      { id: "nb13", name: "Pizza Base", price: 40, desc: "পিজ্জা বেস, homemade pizza।" },
      { id: "nb14", name: "Pastry 4pcs", price: 80, desc: "পেস্ট্রি, flaky baked item।" },
      { id: "nb15", name: "Donuts 4pcs", price: 65, desc: "ডোনাটস, ring-shaped sweet।" },
      { id: "nb16", name: "Muffins 4pcs", price: 70, desc: "মাফিনস, small cakes।" },
      { id: "nb17", name: "Croissant 2pcs", price: 45, desc: "ক্রয়স্যান, French pastry।" },
      { id: "nb18", name: "Bagel 2pcs", price: 35, desc: "বেগেল, ring-shaped bread।" },
      { id: "nb19", name: "Pie", price: 95, desc: "পাই, fruit-filled pastry।" },
      { id: "nb20", name: "Tart", price: 65, desc: "টার্ট, small pastry।" },
      { id: "nb21", name: "Brownie", price: 40, desc: "ব্রাউনি, chocolate square।" },
      { id: "nb22", name: "Cheesecake Slice", price: 85, desc: "চিজকেক স্লাইস, creamy dessert।" },
      { id: "nb23", name: "Bread Rolls 6pcs", price: 30, desc: "ব্রেড রোলস, stuffed rolls।" },
      { id: "nb24", name: "Sandwich Bread", price: 42, desc: "স্যান্ডউইচ ব্রেড, soft texture।" },
      { id: "nb25", name: "Baguette", price: 50, desc: "ব্যাগেট, long French bread।" },
      { id: "nb26", name: "Focaccia", price: 65, desc: "ফোকাচ্চা, Italian flat bread।" },
      { id: "nb27", name: "Pretzel", price: 35, desc: "প্রেটজেল, twisted baked snack।" },
      { id: "nb28", name: "Scone", price: 25, desc: "স্কোন, British baked good।" },
      { id: "nb29", name: "Baking Tray", price: 120, desc: "বেকিং ট্রে, baking equipment।" },
      { id: "nb30", name: "Cake Mould", price: 85, desc: "কেক মোল্ড, cake shaping।" },
      { id: "nb31", name: "Icing Sugar", price: 45, desc: "আইসিং সুগার, cake decoration।" },
      { id: "nb32", name: "Baking Chocolate", price: 75, desc: "বেকিং চকলেট, cooking chocolate।" },
      { id: "nb33", name: "Vanilla Essence", price: 35, desc: "ভ্যানিলা এসেন্স, flavoring agent।" },
      { id: "nb34", name: "Yeast Packet", price: 20, desc: "ইস্ট প্যাকেট, bread rising agent।" },
      { id: "nb35", name: "Bakery Box", price: 15, desc: "বেকারি বক্স, packaging box।" }
    ]
  },

];

// ✅ API routes
app.get("/", (req, res) => res.send("✅ HaatBazar Backend is Running..."));
app.get("/shops", (req, res) => res.json(shops));
app.get("/shops/:id", (req, res) => {
  const shop = shops.find(s => s.id === req.params.id);
  if (!shop) return res.status(404).json({ message: "Shop not found" });
  res.json(shop);
});
app.post("/order", (req, res) => {
  const { items, total } = req.body;
  res.json({ message: "✅ Order received!", items, total });
});

// Run server
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running on port ${PORT}`));